#import "~/gql/fragments/Image"
#import "~/gql/fragments/BlockAssociatedTopicCardsFragment"
#import "~/gql/fragments/BlockBannerFeaturedFragment"
#import "~/gql/fragments/BlockCardWithImageFragment"
#import "~/gql/fragments/BlockHighlight"
#import "~/gql/fragments/BlockImpactNumbersCarouselFragment"
#import "~/gql/fragments/BlockMediaGalleryFragment"
#import "~/gql/fragments/BlockMediaWithTextFragment"
#import "~/gql/fragments/BlockPullQuoteFragment"
#import "~/gql/fragments/BlockRichTextFragment"
#import "~/gql/fragments/BlockSimpleCardsFragment"
#import "~/gql/fragments/BlockCtaFragment"

fragment AllFpb on ElementInterface {
    blocks: allFpb {
        id
        typeHandle

        ...BlockAssociatedTopicCards
        ...BlockBannerFeatured
        ...BlockCardWithImage
        ...BlockHighlight
        ...BlockImpactNumbersCarousel
        ...BlockMediaGallery
        ...BlockMediaWithText
        ...BlockPullQuote
        ...BlockRichText
        ...BlockSimpleCards
        ...BlockCta
    }
}

fragment BlockAssociatedTopicCards on allFpb_associatedTopicCards_BlockType {
    ...BlockAssociatedTopicCardsFragment
}

fragment BlockBannerFeatured on allFpb_bannerFeatured_BlockType {
    ...BlockBannerFeaturedFragment
}

fragment BlockCardWithImage on allFpb_cardWithImage_BlockType {
    ...BlockCardWithImageFragment
}

fragment BlockHighlight on allFpb_highlight_BlockType {
    ...BlockHighlightFragment
}

fragment BlockImpactNumbersCarousel on allFpb_impactNumbersCarousel_BlockType {
    ...BlockImpactNumbersCarouselFragment
}

fragment BlockMediaGallery on allFpb_mediaGallery_BlockType {
    ...BlockMediaGalleryFragment
}

fragment BlockMediaWithText on allFpb_mediaWithText_BlockType {
    ...BlockMediaWithTextFragment
}

fragment BlockPullQuote on allFpb_pullQuote_BlockType {
    ...BlockPullQuoteFragment
}

fragment BlockRichText on allFpb_richText_BlockType {
    ...BlockRichTextFragment
}

fragment BlockSimpleCards on allFpb_simpleCards_BlockType {
    ...BlockSimpleCardsFragment
}

fragment BlockCta on allFpb_callToAction_BlockType {
    ...BlockCtaFragment
}
