#import "~/gql/fragments/Image"
#import "~/gql/fragments/BlockSimpleCardsFragment"
#import "~/gql/fragments/BlockRichTextFragment"
#import "~/gql/fragments/BlockPullQuoteFragment"
#import "~/gql/fragments/BlockMediaGalleryFragment"
#import "~/gql/fragments/BlockMediaWithTextFragment"
#import "~/gql/fragments/BlockFormFragment"

fragment DefaultFpbWithNoCta on ElementInterface {
    blocks: defaultFpbWithNoCta {
        id
        typeHandle
        ...BlockSimpleCards
        ...BlockRichText
        ...BlockPullQuote
        ...BlockMediaWithText
        ...BlockMediaGallery
        ...BlockForm
    }
}

fragment BlockSimpleCards on defaultFpbWithNoCta_simpleCards_BlockType {
    ...BlockSimpleCardsFragment
}

fragment BlockRichText on defaultFpbWithNoCta_richText_BlockType {
    ...BlockRichTextFragment
}

fragment BlockPullQuote on defaultFpbWithNoCta_pullQuote_BlockType {
    ...BlockPullQuoteFragment
}

fragment BlockMediaWithText on defaultFpbWithNoCta_mediaWithText_BlockType {
    ...BlockMediaWithTextFragment
}

fragment BlockMediaGallery on defaultFpbWithNoCta_mediaGallery_BlockType {
    ...BlockMediaGalleryFragment
}

fragment BlockForm on defaultFpbWithNoCta_form_BlockType {
    ...BlockFormFragment
}
