#import "../gql/fragments/BlockMediaGalleryFragment.gql"
#import "../gql/fragments/BlockMediaWithTextFragment.gql"
#import "../gql/fragments/BlockPullQuoteFragment.gql"
#import "../gql/fragments/BlockRichTextFragment.gql"
#import "../gql/fragments/BlockSimpleCardsFragment.gql"
#import "../gql/fragments/BlockCallToActionFragment.gql"
#import "../gql/fragments/BlockFormFragment.gql"

fragment DefaultFpb on ElementInterface {
    blocks: defaultFpb {
        id
        typeHandle

        ... on defaultFpb_mediaGallery_BlockType {
            ...BlockMediaGalleryFragment
        }
        ... on defaultFpb_mediaWithText_BlockType {
            ...BlockMediaWithTextFragment
        }
        ... on defaultFpb_pullQuote_BlockType {
            ...BlockPullQuoteFragment
        }
        ... on defaultFpb_richText_BlockType {
            ...BlockRichTextFragment
        }
        ... on defaultFpb_simpleCards_BlockType {
            ...BlockSimpleCardsFragment
        }
        ... on defaultFpb_callToAction_BlockType {
            ...BlockCallToActionFragment
        }
        ... on defaultFpb_form_BlockType {
            ...BlockFormFragment
        }
    }
}
