#import "~/gql/fragments/Image"
#import "~/gql/fragments/BlockSimpleCardsFragment"
#import "~/gql/fragments/BlockRichTextFragment"
#import "~/gql/fragments/BlockPullQuoteFragment"
#import "~/gql/fragments/BlockMediaGalleryFragment"
#import "~/gql/fragments/BlockMediaWithTextFragment"
#import "~/gql/fragments/BlockFormFragment"

fragment DefaultFpbWithNoCta on ElementInterface {
    blocks: defaultFpbWithNoCta {
        id
        typeHandle
        ... on defaultFpbWithNoCta_simpleCards_BlockType {
            ...BlockSimpleCardsFragment
        }
        ... on defaultFpbWithNoCta_richText_BlockType {
            ...BlockRichTextFragment
        }
        ... on defaultFpbWithNoCta_pullQuote_BlockType {
            ...BlockPullQuoteFragment
        }
        ... on defaultFpbWithNoCta_mediaWithText_BlockType {
            ...BlockMediaWithTextFragment
        }
        ... on defaultFpbWithNoCta_mediaGallery_BlockType {
            ...BlockMediaGalleryFragment
        }
        ... on defaultFpbWithNoCta_form_BlockType {
            ...BlockFormFragment
        }
    }
}
