#import "~/gql/fragments/Image"
#import "~/gql/fragments/BlockMediaGalleryFragment"
#import "~/gql/fragments/BlockMediaWithTextFragment"
#import "~/gql/fragments/BlockPullQuoteFragment"
#import "~/gql/fragments/BlockRichTextFragment"
#import "~/gql/fragments/BlockSimpleCardsFragment"
#import "~/gql/fragments/BlockCallToActionFragment"
#import "~/gql/fragments/BlockFormFragment"

fragment DefaultFpb on ElementInterface {
    blocks: defaultFpb {
        id
        typeHandle

        ...BlockMediaGallery
        ...BlockMediaWithText
        ...BlockPullQuote
        ...BlockRichText
        ...BlockSimpleCards
        ...BlockCallToAction
        ...BlockForm
    }
}

fragment BlockMediaGallery on defaultFpb_mediaGallery_BlockType {
    ...BlockMediaGalleryFragment
}

fragment BlockMediaWithText on defaultFpb_mediaWithText_BlockType {
    ...BlockMediaWithTextFragment
}

fragment BlockPullQuote on defaultFpb_pullQuote_BlockType {
    ...BlockPullQuoteFragment
}

fragment BlockRichText on defaultFpb_richText_BlockType {
    ...BlockRichTextFragment
}

fragment BlockSimpleCards on defaultFpb_simpleCards_BlockType {
    ...BlockSimpleCardsFragment
}

fragment BlockCallToAction on defaultFpb_callToAction_BlockType {
    ...BlockCallToActionFragment
}

fragment BlockForm on allFpb_form_BlockType {
    ...BlockFormFragment
}
