#import "../gql/fragments/BlockBannerFeaturedFragment.gql"
#import "../gql/fragments/BlockCallToActionFragment.gql"
#import "../gql/fragments/BlockSimpleCardsFragment.gql"
#import "../gql/fragments/BlockPullQuoteFragment.gql"
#import "../gql/fragments/BlockMediaGalleryFragment.gql"
#import "../gql/fragments/BlockMediaWithTextFragment.gql"
#import "../gql/fragments/BlockImpactNumbersCarouselFragment.gql"
#import "../gql/fragments/BlockCardWithImageFragment.gql"
#import "../gql/fragments/BlockHighlightFragment.gql"
#import "../gql/fragments/BlockImpactNumberCardsFragment.gql"
#import "../gql/fragments/BlockGridGalleryCardsFragment.gql"

fragment ImpactReportFpb on ElementInterface {
    blocks: impactReportFpb {
        id
        typeHandle

        ... on impactReportFpb_bannerFeatured_BlockType {
            ...BlockBannerFeaturedFragment
        }
        ... on impactReportFpb_callToAction_BlockType {
            ...BlockCallToActionFragment
        }
        ... on impactReportFpb_simpleCards_BlockType {
            ...BlockSimpleCardsFragment
        }
        ... on impactReportFpb_pullQuote_BlockType {
            ...BlockPullQuoteFragment
        }
        ... on impactReportFpb_mediaWithText_BlockType {
            ...BlockMediaWithTextFragment
        }
        ... on impactReportFpb_mediaGallery_BlockType {
            ...BlockMediaGalleryFragment
        }
        ... on impactReportFpb_impactNumbersCarousel_BlockType {
            ...BlockImpactNumbersCarouselFragment
        }
        ... on impactReportFpb_impactNumberCards_BlockType {
            ...BlockImpactNumberCardsFragment
        }
        ... on impactReportFpb_highlight_BlockType {
            ...BlockHighlightFragment
        }
        ... on impactReportFpb_gridGalleryCards_BlockType {
            ...BlockGridGalleryCardsFragment
        }
        ... on impactReportFpb_cardWithImage_BlockType {
            ...BlockCardWithImageFragment
        }
    }
}
