#import "../gql/fragments/Image.gql"
#import "../gql/fragments/BlockMediaGalleryFragment.gql"
#import "../gql/fragments/BlockMediaWithTextFragment.gql"
#import "../gql/fragments/BlockPullQuoteFragment.gql"
#import "../gql/fragments/BlockRichTextFragment.gql"
#import "../gql/fragments/BlockSimpleCardsFragment.gql"
#import "../gql/fragments/BlockCallToActionFragment.gql"

fragment MEAPDefaultFpb on ElementInterface {
    blocks: meapFlexiblePageBlockCollections_defaultFpb {
        id
        typeHandle

        ... on meapFlexiblePageBlockCollections_defaultFpb_mediaGallery_BlockType {
            ...BlockMediaGalleryFragment
        }
        ...on meapFlexiblePageBlockCollections_defaultFpb_mediaWithText_BlockType {
            ...BlockMediaWithTextFragment
        }
        ... on meapFlexiblePageBlockCollections_defaultFpb_pullQuote_BlockType {
            ...BlockPullQuoteFragment
        }
        ... on meapFlexiblePageBlockCollections_defaultFpb_richText_BlockType {
            ...BlockRichTextFragment
        }
        ... on meapFlexiblePageBlockCollections_defaultFpb_simpleCards_BlockType {
            ...BlockSimpleCardsFragment
        }
        ... on meapFlexiblePageBlockCollections_defaultFpb_callToAction_BlockType {
            ...BlockCallToActionFragment
        }
    }
}

