#import "../gql/fragments/Image.gql"
#import "../gql/fragments/BlockAssociatedTopicCardsFragment.gql"
#import "../gql/fragments/BlockBannerFeaturedFragment.gql"
#import "../gql/fragments/BlockCardWithImageFragment.gql"
#import "../gql/fragments/BlockHighlightFragment.gql"
#import "../gql/fragments/BlockImpactNumbersCarouselFragment.gql"
#import "../gql/fragments/BlockMediaGalleryFragment.gql"
#import "../gql/fragments/BlockMediaWithTextFragment.gql"
#import "../gql/fragments/BlockPullQuoteFragment.gql"
#import "../gql/fragments/BlockRichTextFragment.gql"
#import "../gql/fragments/BlockSimpleCardsFragment.gql"
#import "../gql/fragments/BlockCallToActionFragment.gql"

fragment MEAPAllFpb on ElementInterface {
    blocks: meapFlexiblePageBlockCollections_allFpb {
        id
        typeHandle

        ... on meapFlexiblePageBlockCollections_allFpb_associatedTopicCards_BlockType {
            ...BlockAssociatedTopicCardsFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_bannerFeatured_BlockType {
            ...BlockBannerFeaturedFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_cardWithImage_BlockType {
            ...BlockCardWithImageFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_highlight_BlockType {
            ...BlockHighlightFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_impactNumbersCarousel_BlockType {
            ...BlockImpactNumbersCarouselFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_mediaGallery_BlockType {
            ...BlockMediaGalleryFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_mediaWithText_BlockType {
            ...BlockMediaWithTextFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_pullQuote_BlockType {
            ...BlockPullQuoteFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_richText_BlockType {
            ...BlockRichTextFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_simpleCards_BlockType {
            ...BlockSimpleCardsFragment
        }
        ... on meapFlexiblePageBlockCollections_allFpb_callToAction_BlockType {
            ...BlockCallToActionFragment
        }
    }
}
