allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
  unrs-resolver: true
  vue-demi: true
engineStrict: true
minimumReleaseAgeExclude:
  - '@ucla-library-monorepo/ucla-library-website-components@1.78.2'
  - '@ucla-library/component-library-nuxt-module@1.3.50'
