fragment BlockImpactNumberCardsFragment on ElementInterface {
    id
    typehandle
    sectionSummary: summary
    sectionTitle: titleGeneral
    impactNumberCards {
        ... on impactNumberCards_impactNumberCard_BlockType {
            id
            title: titleGeneral
            text: description
            impactNumber
        }
    }
}
