fragment BlockBannerFeaturedFragment on ElementInterface {
    id
    typeHandle
    sectionTitle: titleGeneral
    content: bannerFeatured {
        ... on bannerFeatured_internalContent_BlockType {
            id
            contentLink {
                contentType: sectionHandle
                title
                to: uri
                summary
                physicalDigital
                workshopOrEventSeriesType
                eventType {
                    title
                }
                eventDescription
                projectCategory: format
                articleCategory: articleCategories {
                    title
                }
                projectByline1: meapProjectTopic {
                    ... on meapProjectTopics_Category {
                        id
                        title
                    }
                }
                startDateWithTime
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                endDateWithTime
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                startDate
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                endDate
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                articleByline1: staffMember {
                    id
                    slug
                    uri
                    url
                    title
                }
                articleByline2: postDate
                articleLocations: associatedLocations {
                    id
                    title
                    to: uri
                }
                projectLocations: region {
                    ... on meapProjectRegion_Category {
                        id
                        title
                    }
                }
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        image {
                            ...Image
                        }
                    }
                }
            }
        }
        ... on bannerFeatured_externalContent_BlockType {
            id
            image {
                ...Image
            }
            title: titleGeneral
            summary
            alignment
            # TODO using internal locations for external content will need component update
            # locations: associatedLocations {
            #       id
            #       title
            #       to: uri
            # }
            byline1
            byline2
            to: buttonUrl
            category
            contentType
        }
    }
}
