fragment BlockMediaGalleryFragment on ElementInterface {
    id
    typeHandle
    titleGeneral
  	sectionSummary: summary
    mediaGallery {
        id
        ... on mediaGallery_image_BlockType {
          id
          captionTitle: captionHeading
          captionText: caption
          altText
          sortOrder
          image: imageFile {
          	...Image
          }
        }
    }
}
