fragment BlockSimpleCardsFragment on ElementInterface {
    id
    typeHandle
    sectionTitle: titleGeneral
    sectionSummary: summary
    cards: meapflexiblePageBlocks_simpleCards {
        ... on meapflexiblePageBlocks_simpleCards_internalResource_BlockType {
            id
            typeHandle
            contentLink {
                id
                uri
                title
                summary
                externalResourceUrl
            }
        }
        ... on meapflexiblePageBlocks_simpleCards_externalResource_BlockType {
            id
            typeHandle
            title: titleGeneral
            summary
            externalLink
        }
    }
}
