#import "../gql/fragments/MediaAsset.gql"

fragment BlockMediaGalleryExtraFieldsFragment on ElementInterface {
    id
    sectionTitle: titleGeneral
    richTextSimplified
    mediaGallery: mediaGalleryExtraFields {
        dataId: id
        captionTitle: captionHeading
        captionText: caption
        altText
        sortOrder
        linkUrl
        linkText
        credit
        ... on mediaGalleryExtraFields_image_BlockType {
            item: imageFile {
                ...MediaAsset
            }
        }
        ... on mediaGalleryExtraFields_audio_BlockType {
            item: audioFile {
                ...MediaAsset
            }
            embedCode: audioEmbedCode
            coverImage {
                ...MediaAsset
            }
        }
        ... on mediaGalleryExtraFields_video_BlockType {
            item: videoFile {
                ...MediaAsset
            }
            embedCode: embedCode
            coverImage {
                ...MediaAsset
            }
        }
    }
}
