fragment BlockBannerFeaturedFragment on ElementInterface {
    typeHandle
    id
    sectionTitle: titleGeneral
    content: meapflexiblePageBlocks_bannerFeatured {
        ... on meapflexiblePageBlocks_bannerFeatured_internalContent_BlockType {
            id
            contentLink {
                contentType: sectionHandle
                title
                to: uri
                summary
                projectCategory: format
                # eventCategory: eventType
                articleCategory: articleCategories {
                    title
                }
                projectByline1: meapProjectTopic {
                    ... on meapProjectTopics_Category {
                        id
                        title
                    }
                }
                articleByline1: staffMember {
                  id
                  to: uri
                  title
                }
                articleByline2: postDate
                # eventByline1: dateStartTime
                # eventByline2: dateEndTime

                articleLocations: associatedLocations {
                    id
                    title
                    to: uri
                }
                # eventLocations: eventLocation
                projectLocations: region {
                    ... on meapProjectRegion_Category {
                        id
                        title
                    }
                }
                # aligment will be defualts to left
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        image {
                            ...Image
                        }
                    }
                }
            }
        }
        ... on meapflexiblePageBlocks_bannerFeatured_externalContent_BlockType {
            id
            image {
                ...Image
            }
            title: titleGeneral
            summary
            alignment
            location
            byline1
            byline2
            to: buttonUrl
            category
            contentType
        }
    }
}
