fragment BlockMediaWithTextFragment on ElementInterface {
    id
    typeHandle
    sectionTitle: titleGeneral
    sectionSummary: summary
    mediaWithText {
        ... on mediaWithText_mediaEmbed_BlockType {
            id
            titleEmbed
            description
            coverImage {
                ...Image
            }
            buttonText
            buttonUrl
            embedCode
            typeMedia
        }
        ... on mediaWithText_mediaUpload_BlockType {
            id
            titleUpload
            description
            buttonText
            buttonUrl
            coverImage {
                ...Image
            }
            upload {
                ...Image
            }
            typeMedia
        }
    }
}
