fragment BlockCardWithImageFragment on ElementInterface {
    id
    typeHandle
    cardWithImage: meapflexiblePageBlocks_cardWithImage {
        id
        ... on meapflexiblePageBlocks_cardWithImage_cardWithImage_BlockType {
            id
            src: image {
                ...Image
            }
            imageAltText
            contentLink {
                id
                to: url
                uri
                title
                date {
                    startDate
                    endDate
                }
                associatedLocations {
                    id
                    title
                    to: uri
                }
            }
            summary: shortDescription
        }
    }
}
