fragment BlockMediaGalleryFragment on ElementInterface  {
    id
    titleGeneral
    mediaGallery {
        id
        ... on mediaGallery_image_BlockType {
          id
          # ...Image
          # image { id url }

          captionTitle: captionHeading
          captionText: caption
          altText
          sortOrder
          image: imageFile(altText: "") {
                id
                img
                title
                ... on mediaAndDocuments_Asset {
                    id
                    title
                    kind
                    width
                    src: url
                    height
                }
            }
        }
    }
}
