fragment BlockAssociatedTopicCardsFragment on ElementInterface {
    id
    typeHandle
    sectionSummary: summary
    sectionTitle: titleGeneral
    associatedTopicsFlexiblePageBlock: meapflexiblePageBlocks_associatedTopics {
        ... on meapflexiblePageBlocks_associatedTopics_associatedTopics_BlockType {
            id
            topics {
                title
                typeHandle
                externalResourceUrl
                uri
                text: summary
                uri
            }
        }
    }
}
