fragment BlockAssociatedTopicCardsFragment on ElementInterface {
    id
    typeHandle
    sectionText: summary
    sectionTitle: titleGeneral
    associatedTopicsFlexiblePageBlock {
        ... on associatedTopicsFlexiblePageBlock_associatedTopics_BlockType {
            id
            topics {
                title
                typeHandle
                to: uri
                text: summary
                uri
            }
        }
    }
}
