#import "~/gql/fragments/Image"
#import "~/gql/fragments/BlockDividerFragment"
#import "~/gql/fragments/BlockMediaWithTextFragment"
#import "~/gql/fragments/BlockPullQuoteFragment"
#import "~/gql/fragments/BlockRichTextFragment"
#import "~/gql/fragments/BlockSimpleCardsFragment"

fragment DefaultFpbWithNoCta on ElementInterface {
    blocks: defaultFpbWithNoCta {
        id
        typeHandle
        ...BlockDivider
        ...BlockMediaWithText
        ...BlockPullQuote
        ...BlockRichText
        ...BlockSimpleCards
    }
}

fragment BlockDivider on defaultFpbWithNoCta_divider_BlockType {
    ...BlockDividerFragment
}

fragment BlockMediaWithText on defaultFpbWithNoCta_mediaWithText_BlockType {
    ...BlockMediaWithTextFragment
}

fragment BlockPullQuote on defaultFpbWithNoCta_pullQuote_BlockType {
    ...BlockPullQuoteFragment
}

fragment BlockRichText on defaultFpbWithNoCta_richText_BlockType {
    ...BlockRichTextFragment
}

fragment BlockSimpleCards on defaultFpbWithNoCta_simpleCards_BlockType {
    ...BlockSimpleCardsFragment
}

fragment BlockMediaWithText on defaultFpbWithNoCta_mediaWithText_BlockType {
    id
    sectionTitle: titleGeneral
    sectionSummary: summary
    mediaWithText {
        ... on mediaWithText_mediaLink_BlockType {
            id
            titleLink
            description
            coverImage {
                ...Image
            }
            buttonText
            buttonUrl
            linkToMedia
            typeMedia
        }
        ... on mediaWithText_mediaUpload_BlockType {
            id
            titleUpload
            description
            buttonText
            buttonUrl
            coverImage {
                ...Image
            }
            upload {
                ...Image
            }
            typeMedia
        }
    }
}
