fragment FlexibleBlocks on ElementInterface {
    blocks: allFlexiblePageBlocks {
        id
        typeHandle
        ...BlockRichText
        ...BlockDivider
        ...BlockCta
        ...BlockImageWithTextOverlay
        ...BlockFaqs
    }
}

# TODO Define all blocks here as fragments

fragment BlockRichText on allFlexiblePageBlocks_richText_BlockType {
    text
}

fragment BlockDivider on allFlexiblePageBlocks_divider_BlockType {
    divider
}

fragment BlockCta on allFlexiblePageBlocks_ctaBlockContentWidth_BlockType {
    innerBlocks: ctaBlockContentWidth {
        a
        ... on ctaBlockContentWidth_ctaBlockContentWidth_BlockType {
            id
            title: titleCtaContentWidth
            description: shortDescription
            buttonUrl: urlButtonUrl
            buttonText: urlButtonText
            icon
        }
    }
}

fragment BlockImageWithTextOverlay on imageWithTextOverlay_imageWithTextOverlay_BlockType {
    id
    title: imageWithTextOverlayTitle
    description: shortDescription
    imageAltText
    image {
        url
    }
    imageAlignment: alignment
    urlButtonText
    urlButtonUrl
}

fragment BlockFaqs on allFlexiblePageBlocks_faqs_BlockType {
    id
    subheader
    shortDescription
    faqs {
        ... on faqs_questionAnswer_BlockType {
            id
            question
            answer
        }
    }
}