#import "~/gql/fragments/Image"

fragment FlexibleBlocks on ElementInterface {
    blocks: allFlexiblePageBlocks {
        id
        typeHandle

        ...BlockCardWithImage
        ...BlockCtaBlockTwoUp
        ...BlockCta
        ...BlockDivider
        ...BlockMediaWithText
        ...BlockBannerFeatured
        ...BlockImageWithTextOverlay
        ...BlockImpactNumbersCarousel
        ...BlockMediaGallery
        ...BlockPullQuote
        ...BlockRichText
        ...BlockHelpTopicCards
        ...BlockSimpleCards
        ...BlockHighlight
        ...BlockForm
    }
}

# Define all blocks here as fragments

fragment BlockCardWithImage on allFlexiblePageBlocks_cardWithImage_BlockType {
    id
    cardWithImage {
        id
        ... on cardWithImage_cardWithImage_BlockType {
            id
            image {
                ...Image
            }
            imageAltText
            contentLink {
                id
                to: url
                uri
                title
                date {
                    startDate
                    endDate
                }
                associatedLocations {
                    id
                    title
                    to: uri
                }
            }
            shortDescription
        }
    }
}

fragment BlockCtaBlockTwoUp on allFlexiblePageBlocks_ctaBlock2Up_BlockType {
    id
    ctaBlock2Up {
        id
        ... on ctaBlock2Up_ctaBlock2Up_BlockType {
            id
            text: shortDescription
            name: urlButtonText
            to: urlButtonUrl
            title: titleCTA2Up
            svgName: icon
            backgroundColor
            isSizeSmall
        }
    }
}

fragment BlockCta on allFlexiblePageBlocks_ctaBlockContentWidth_BlockType {
    innerBlocks: ctaBlockContentWidth {
        ... on ctaBlockContentWidth_ctaBlockContentWidth_BlockType {
            id
            title: titleCtaContentWidth
            description: shortDescription
            buttonUrl: urlButtonUrl
            buttonText: urlButtonText
            icon
        }
    }
}

fragment BlockDivider on allFlexiblePageBlocks_divider_BlockType {
    id
    divider
}

fragment BlockMediaWithText on allFlexiblePageBlocks_mediaWithText_BlockType {
    id
    mediaWithText {
        ... on mediaWithText_mediaWithText_BlockType {
            id
            sectionHeader
            shortDescription
            buttonText
            mediaType
            mediaWithTextLink
            downloadAssetLink {
                id
                url
            }
            image {
                ...Image
            }
        }
    }
}

fragment BlockBannerFeatured on allFlexiblePageBlocks_bannerFeatured_BlockType {
    id
    bannerFeatured {
        ... on bannerFeatured_bannerFeatured_BlockType {
            id
            contentLink {
                url
                to: uri
                title
                prompt: buttonText
                date {
                    startDate
                    endDate
                }
                associatedLocations {
                    id
                    title
                    to: uri
                }
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                        altText
                    }
                }
            }
            alignment
        }
    }
}

fragment BlockImageWithTextOverlay on allFlexiblePageBlocks_imageWithTextOverlay_BlockType {
    id
    imageWithTextOverlay {
        id
        ... on imageWithTextOverlay_imageWithTextOverlay_BlockType {
            id
            title: imageWithTextOverlayTitle
            description: shortDescription
            imageAltText
            image {
                url
            }
            imageAlignment: alignment
            urlButtonText
            urlButtonUrl
        }
    }
}

fragment BlockImpactNumbersCarousel on allFlexiblePageBlocks_impactNumbersCarousel_BlockType {
    id
    impactNumbersCarousel {
        id
        ... on impactNumbersCarousel_impactNumbersCarousel_BlockType {
            id
            largeText
            mediumText
            smallDescriptor
            image {
                url
            }
            imageAltText
        }
    }
}

fragment BlockMediaGallery on allFlexiblePageBlocks_mediaGallery_BlockType {
    id
    mediaGallery {
        id
        ... on mediaGallery_image_BlockType {
            id
            image {
                id
                url
            }
            captionTitle
            captionText
            altText
        }
    }
}

fragment BlockPullQuote on allFlexiblePageBlocks_pullQuote_BlockType {
    id
    pullQuote {
        ... on pullQuote_pullQuote_BlockType {
            text
            attribution
        }
    }
}

fragment BlockRichText on allFlexiblePageBlocks_richText_BlockType {
    richText
}

fragment BlockHelpTopicCards on allFlexiblePageBlocks_helpTopicCards_BlockType {
    id
    helpTopicCards {
        ... on helpTopicCards_helpTopicCards_BlockType {
            id
            contentLink {
                id
                url
                to: uri
                title
                text: shortDescription
                iconName: illustrationsResourcesAndServices
            }
        }
    }
}

fragment BlockSimpleCards on allFlexiblePageBlocks_simpleCards_BlockType {
    id
    simpleCards {
        ... on simpleCards_simpleCard_BlockType {
            id
            title: titleSimpleCard
            contentLink {
                id
                url
                title
                text: summary
            }
            summary
            externalLink
        }
    }
}

fragment BlockHighlight on allFlexiblePageBlocks_highlight_BlockType {
    id
    highlight {
        ... on highlight_highlight_BlockType {
            id
            contentLink {
                id
                url
                to: uri
                title
                prompt: buttonText
                text: shortDescription
                date {
                    startDate
                    endDate
                }
                associatedLocations {
                    id
                    title
                    to: uri
                }
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                        altText
                    }
                }
            }
        }
    }
}

fragment BlockFormFragment on allFlexiblePageBlocks_form_BlockType {
    form
}
