fragment FlexibleBlocks on ElementInterface {
    allFlexiblePageBlocks {
        id
        typeHandle
        ...BlockRichText
        ...BlockDivider
        ...BlockCta
    }
}

fragment BlockRichText on allFlexiblePageBlocks_richText_BlockType {
    text
}

fragment BlockDivider on allFlexiblePageBlocks_divider_BlockType {
    divider
}

fragment BlockCta on allFlexiblePageBlocks_ctaBlockContentWidth_BlockType {
    innerBlocks: ctaBlockContentWidth {
        a
        ... on ctaBlockContentWidth_ctaBlockContentWidth_BlockType {
            id
            title: titleCtaContentWidth
            description: shortDescription
            buttonUrl: urlButtonUrl
            buttonText: urlButtonText
            icon
        }
    }
}
