fragment Image on AssetInterface {
    id
    src: url(transform: "fullscreen")
    height(transform: "fullscreen")
    width(transform: "fullscreen")
    srcset(sizes: ["375", "960", "1280", "1920", "2560"])
    alt: altText
    focalPoint
}
