#import "~/gql/fragments/Image"

query ArticleNewsList {
    entries(section: "article", orderBy: "dateCreated") {
        ... on article_article_Entry {
            id
            articleCategories {
                title
            }
            title
            uri
            to: uri
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }
            description: summary
            authors: staffMember {
                title
            }
            date: dateCreated
        }
    }
    entryCount
}
