#import "~/gql/fragments/Image"

query ArticleList($articleType: QueryArgument!) {
  entries(
    section: "article"
    orderBy: "postDate DESC"
    articleType: [$articleType]
  ) {
    ... on article_article_Entry {
      title
      to: uri
      heroImage {
        ... on heroImage_heroImage_BlockType {
          id
          image {
            ...Image
          }
        }
      }
      description: summary
      authors: staffMember {
        title
      }
      date: postDate
      articleCategories {
        id
        title
        uri
      }
    }
  }

  entry(section: "listingNews") {
    ... on listingNews_listingNews_Entry {
      title
      text: summary
      ... on listingNews_listingNews_Entry {
        featuredNews {
          ... on article_article_Entry {
            title
            articleCategories {
              id
              title
              uri
            }
            text: summary
            to: uri
            heroImage {
              ... on heroImage_heroImage_BlockType {
                id
                image {
                  ...Image
                }
              }
            }
            postDate
          }
        }
      }
    }
  }
}
