#import "~/gql/fragments/Image"
#import "~/gql/fragments/collections/AllFpb"

query ArticleNewsDetail($slug: [String!]) {
    entry(section: "article", slug: $slug) {
        ... on article_article_Entry {
            postDate
            id
            slug
            uri
            sectionHandle
            title
            text: summary
            dateCreated
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }
            category: articleCategories {
                id
                title
                uri
            }
            contributors {
                ... on contributors_staffMember_BlockType {
                    byline
                    staffMember {
                        title
                        to: slug
                    }
                }
                ... on contributors_externalContributor_BlockType {
                byline
                title: contributor
                }
            }
            locations: associatedLocations {
                id
                title
                to: uri
                ... on location_location_Entry {
                    id
                    email
                }
            }
            department {
                id
                title
                uri
            }
            associatedStaffMember {
                ... on staffMember_staffMember_Entry {
                    id
                    email
                    phone: phoneNumber
                    jobTitle: staffMemberJobTitle
                    nameFirst
                    nameLast
                    to: slug
                    consultation: bookAConsultation
                    departments: staffDepartment(orderBy: "level") {
                        id
                        title
                    }
                    locations: staffAssociatedLocations {
                        id
                        title
                        to: slug
                    }
                    image: staffPortrait {
                        ...Image
                    }
                }
            }
            ...AllFpb
        }
    }
}
