#import "~/gql/fragments/Image"

query ArticleNewsList {
    entries(section: "meapArticle", orderBy: "dateCreated") {
        ... on meapArticle_meapArticle_Entry {
            id
            articleCategories {
                title
            }
            title
            uri
            to: slug
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }
            description: summary
            authors: staffMember {
                title
            }
            date: dateCreated
        }
    }
    entryCount
}
