#import "~/gql/fragments/Image"

query ArticleNewsList($articleType: QueryArgument!) {
  entries(section: "article", orderBy: "dateCreated", articleType: [$articleType]) {
        ... on article_article_Entry {
            id
            articleCategories {
                title
            }
            title
            to: uri
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }
            description: summary
            authors: staffMember {
                title
            }
            date: dateCreated
        }
    }
    entryCount
}
