#import "~/gql/fragments/Image"
#import "~/gql/fragments/collections/MEAPAllFpb"

query ArticleNewsDetail($slug: [String!]) {
    entry(section: "meapArticle", slug: $slug) {
        ... on meapArticle_meapArticle_Entry {
            postDate
            id
            sectionHandle
            uri
            slug
            to: slug
            title
            text: summary
            dateCreated
            category: articleCategories {
                title
                uri
            }
            contributors {
                ... on contributors_staffMember_BlockType {
                    byline
                    staffMember {
                        title
                        to: slug
                    }
                }
                ... on contributors_externalContributor_BlockType {
                byline
                title: contributor
                }
            }
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }

            articleTopics {
                title
            }

            byline: staffMember {
                id
                slug
                title
            }
            date: dateUpdated
        }

        ...MEAPAllFpb
    }
}
