#import "~/gql/fragments/Image"
#import "~/gql/fragments/collections/AllFpb"

query ArticleNewsDetail($slug: [String!]) {
  entry(section: "article", slug: $slug) {
    ... on article_article_Entry {
      id
      articleType
      title
      text: summary
      dateCreated
      heroImage {
        ... on heroImage_heroImage_BlockType {
          id
          image {
            ...Image
          }
        }
      }
      category: articleCategories {
        id
        title
        uri
      }
      byline: staffMember {
        id
        ... on staffMember_staffMember_Entry {
          id
          nameFirst
          nameLast
          fullName
        }
      }
      locations: associatedLocations {
        id
        title
        uri
        ... on location_location_Entry {
          id
          email
        }
      }
      department {
        id
        title
        uri
      }
    }
    ...AllFpb
  }
}
