#import "~/gql/fragments/Image"
#import "~/gql/fragments/collections/AllFpb"

query ArticleNewsDetail($slug: [String!]) {
  entry(section: "article", slug: $slug) {
    ... on article_article_Entry {
      id
      articleType
      title
      heroImage {
        ... on heroImage_heroImage_BlockType {
          id
          image {
                ...Image
          }
        }
      }
      articleCategories {
        id
        title
        uri
      }
      staffMember {
        id
        ... on staffMember_staffMember_Entry {
          id
          nameFirst
          nameLast
        }
      }
      associatedLocations {
        id
        title
        uri
      }
      department {
        id
        title
        uri
      }
      description: summary
    }
    ...AllFpb
  }
}

# "heroImage": [
#   {
#     "id": "4423",
#     "image": [
#       {
#         "id": "5230",
#         "src": "https://static.library.ucla.edu/craftassetstest/_fullscreen/lirary-workshop.jpg",
#         "height": 1277,
#         "width": 2560,
#         "srcset": "https://static.library.ucla.edu/craftassetstest/_375xAUTO_crop_center-center_none/lirary-workshop.jpg 375w, https://static.library.ucla.edu/craftassetstest/_960xAUTO_crop_center-center_none/lirary-workshop.jpg 960w, https://static.library.ucla.edu/craftassetstest/_1280xAUTO_crop_center-center_none/lirary-workshop.jpg 1280w, https://static.library.ucla.edu/craftassetstest/_1920xAUTO_crop_center-center_none/lirary-workshop.jpg 1920w, https://static.library.ucla.edu/craftassetstest/_2560xAUTO_crop_center-center_none/lirary-workshop.jpg 2560w",
#         "alt": "Library Workshop",
#         "focalPoint": [
#           0.5,
#           0.5
#         ]
#       }
#     ]
#   }
# ],
