#import "../gql/fragments/Image.gql"
#import "../gql/fragments/collections/AllFpb.gql"

query AskUs {
  entry(section: "askUs") {
    ... on askUs_askUs_Entry {
      title
      summary
      ...AllFpb
    }
  }
}
