#import "~/gql/fragments/Image"

query ExploreCollectionsList {
  entry(section: "listingExploreCollections") {
    title
    summary
    ... on listingExploreCollections_listingExploreCollections_Entry {
      associatedTopics {
        title
        text: summary
        to: uri
        externalResourceUrl
        iconName: illustrationsResourcesAndServices
      }
    }
  }
  entries(section: "collection", orderBy: "postDate DESC") {
    title
    text: summary
    category: physicalDigital
    to: uri
    heroImage {
      ... on heroImage_heroImage_BlockType {
        id
        image {
          ...Image
        }
      }
    }
  }
}
