#import "~/gql/fragments/collections/AllFpb"
query CollectionsList {
    entry(section: "listingCollections") {
        ... on listingCollections_listingCollections_Entry {
            title
            summary
            featuredResourcesSection {
                ... on featuredResourcesSection_featuredResources_BlockType {
                    titleGeneral
                    sectionSummary
                    featuredResources {
                        title
                        text: summary
                        to: uri
                        externalResourceUrl
                        iconName: illustrationsResourcesAndServices
                    }
                }
            }
            featuredCollectionsSection {
                ... on featuredCollectionsSection_featuredCollections_BlockType {
                    titleGeneral
                    sectionSummary
                    featuredCollections {
                        title
                        summary
                        # yes, we do need both of these slugs
                        titleLink: slug
                        slug
                        heroImage {
                            ... on heroImage_heroImage_BlockType {
                                id
                                image {
                                    ...Image
                                }
                            }
                        }
                        button: buttonUrl {
                            ... on buttonUrl_button_BlockType {
                                id
                                buttonText
                                buttonUrl
                            }
                        }
                        category: physicalDigital
                    }
                }
            }
            ...AllFpb
        }
    }
    entries(
        section: "article"
        relatedToCategories: [{ title: "collections" }]
        orderBy: "postDate DESC"
        limit: 3
    ) {
        title
        text: summary
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
            }
        }
        articleCategories {
            title
        }
        to: uri
        postDate
    }
    entryCount(
        section: "article"
        relatedToCategories: [{ title: "collections" }]
        orderBy: "postDate DESC"
        limit: 3
    )
}
