#import "~/gql/fragments/Image"

query CollectionDetail($slug: [String!]) {
    entry(section: "collection", slug: $slug) {
        id
        physicalDigital
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
                altText
            }
        }
        title
        text: summary
        subjectAreas {
        title
        }
        collectionFormats {
            title
        }
        languageOfOrigin
        uri
        buttonUrl {
            ... on buttonUrl_button_BlockType {
                buttonText
                buttonUrl
            }
        }
        endowment {
            ... on endowment_endowments_Entry {
                id
                endowmentDescription
                summary
                title
                donors {
                    firstName
                }
            }
            heroImage {
                ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
                altText
                uri
                title
                }
            }
        }
        associatedStaffMember {
            email
            phoneNumber
            staffMemberJobTitle
            nameFirst
            nameLast
            uri
            bookAConsultation
            staffDepartment {
                title
            }
            staffPortrait {
                ...Image
            }
        }
    }
}

# fragment Image on AssetInterface {
#   id
#   src: url(transform: "fullscreen")
#   height(transform: "fullscreen")
#   width(transform: "fullscreen")
#   srcset(sizes: ["375", "960", "1280", "1920", "2560"])
#   alt: title
#   focalPoint
# }
