query AccessCollectionsListing {
  entry(section: "listingAccessCollections") {
    title
    summary
    ... on listingAccessCollections_listingAccessCollections_Entry {
      accessCollections {
        title
        text: summary
        uri
        externalResourceUrl
        iconName: illustrationsResourcesAndServices
          ... on externalResource_externalResource_Entry {
          id
        }
        category
        typeHandle
        serviceOrResourceType
        workshopOrEventSeriesType
      }
      associatedTopics {
        title
        text: summary
        to : uri
        externalResourceUrl
        iconName: illustrationsResourcesAndServices
        category
        typeHandle
        serviceOrResourceType
        workshopOrEventSeriesType
      }
    }
  }
}
