#import "~/gql/fragments/Image"
query EndowmentsList {
  entry(section: "listingEndowments") {
    ... on listingEndowments_listingEndowments_Entry {
      title
      text: summary
          featuredEndowments {
        ... on featuredEndowments_featuredEndowments_BlockType {
          titleGeneral
          sectionSummary
          featuredEndowments {
            text: summary
            uri
            title
            alternativeName {
              languageAltName
              fullName
            }
            heroImage {
              ... on heroImage_heroImage_BlockType {
                image {
                  ...Image
                }
              }
            }
          }
        }
      }
    }
  }
  entries(section: "endowment", orderBy: "title ASC") {
    title
    alternativeName {
      languageAltName
      fullName
    }
    description: summary
    to: uri
    heroImage {
      ... on heroImage_heroImage_BlockType {
        id
        image {
          ...Image
        }
        altText
      }
    }
    donors {
      ... on donors_donor_BlockType {
        firstName
        lastName
      }
    }
  }
} 
