#import "../gql/fragments/Image.gql"
#import "../gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql"
#import "../gql/fragments/collections/ExhibitionsAndCollectionsFpb.gql"
query EventDetail($slug: [String!]) {
    event: entry(section: "event", slug: $slug) {
        ... on event_event_Entry {
            id
            uri
            typehandle
            sectionHandle
            title: eventTitle
            eventLocation: location {
                title
                to: publicUrl
            }
            image: heroImage {
                ... on heroImage_heroImage_BlockType {
                    image {
                        ...Image
                    }
                }
            }
            to: uri
            slug
            libcalId
            publicUrl
            startDateWithTime
                @formatDateTime(
                    format: "Y-m-d\\TH:i"
                    timezone: "America/Los_Angeles"
                )
            endDateWithTime
                @formatDateTime(
                    format: "Y-m-d\\TH:i"
                    timezone: "America/Los_Angeles"
                )
            eventType {
                ... on eventType_Category {
                    id
                    title
                }
            }
            eventDescription
            associatedLocations {
                ... on location_location_Entry {
                    id
                    to: uri
                    title
                    summary
                }
            }
            requiresRegistration
            libcalRegistrationOpened
            libcalRegistrationClosed
            libcalPhysicalSeats
            libcalPhysicalSeatsTaken
            libcalOnlineSeats
            libcalOnlineSeatsTaken
            libcalWaitlist
            onlineProvider: libcalEventOnlineProvider
            onlineJoinURL: onlineEventUrl
            eventTags {
                ... on eventTags_Tag {
                    id
                    title
                }
            }
            presenter
            moreInformation
            eventOwner
        }
    }
    associatedSeries: entries(
        section: "workshopOrEventSeries"
        relatedToEntries: { section: "event", slug: $slug }
    ) {
        title
        sectionHandle
        workshopOrEventSeriesType
        text: summary
        image: heroImage {
            ... on heroImage_heroImage_BlockType {
                image {
                    ...Image
                }
            }
        }
        to: uri
        startDate
            @formatDateTime(
                format: "Y-m-d\\TH:i"
                timezone: "America/Los_Angeles"
            )
        endDate
            @formatDateTime(
                format: "Y-m-d\\TH:i"
                timezone: "America/Los_Angeles"
            )
        ongoing
    }
    eventSeries: entry(section: "workshopOrEventSeries", slug: $slug) {
        id

        ... on workshopOrEventSeries_workshopOrEventSeries_Entry {
            id
            workshopOrEventSeriesType
            sectionHandle
            typeHandle
            uri
            slug
            title
            summary
            startDate
                @formatDateTime(
                    format: "Y-m-d\\TH:i"
                    timezone: "America/Los_Angeles"
                )
            endDate
                @formatDateTime(
                    format: "Y-m-d\\TH:i"
                    timezone: "America/Los_Angeles"
                )
            ongoing
            eventLocation: location {
                title
                to: publicUrl
            }
            associatedLocations {
                ... on location_location_Entry {
                    id
                    to: uri
                    title
                    summary
                }
            }
            image: heroImage {
                ... on heroImage_heroImage_BlockType {
                    image {
                        ...Image
                    }
                }
            }
            associatedTopics {
                id
                title
                text: summary
                uri
                externalResourceUrl
                illustration
            }
            ...DefaultFpbWithCardsAndHighlight
        }
    }

    pastEvents: entries(
        section: "event"
        orderBy: "startDateWithTime DESC"
        startDateWithTime: "< now"
        relatedToEntries: { section: "workshopOrEventSeries", slug: $slug }
    ) {
        title: eventTitle
        uri
        sectionHandle
        eventType {
            title
        }
        startDateWithTime
            @formatDateTime(
                format: "Y-m-d\\TH:i:s"
                timezone: "America/Los_Angeles"
            )
        endDateWithTime
            @formatDateTime(
                format: "Y-m-d\\TH:i:s"
                timezone: "America/Los_Angeles"
            )
        associatedLocations {
            title
        }
        eventLocation: location {
            title
        }
        image: heroImage {
            ... on heroImage_heroImage_BlockType {
                image {
                    ...Image
                }
            }
        }
        category: eventType {
            ... on eventType_Category {
                id
                title
            }
        }
    }

    upcomingEvents: entries(
        section: "event"
        orderBy: "startDateWithTime ASC"
        startDateWithTime: ">= now"
        relatedToEntries: { section: "workshopOrEventSeries", slug: $slug }
    ) {
        title: eventTitle
        uri
        sectionHandle
        eventType {
            title
        }
        startDateWithTime
            @formatDateTime(
                format: "Y-m-d\\TH:i:s"
                timezone: "America/Los_Angeles"
            )
        endDateWithTime
            @formatDateTime(
                format: "Y-m-d\\TH:i:s"
                timezone: "America/Los_Angeles"
            )
        associatedLocations {
            title
        }
        eventLocation: location {
            title
        }
        image: heroImage {
            ... on heroImage_heroImage_BlockType {
                image {
                    ...Image
                }
            }
        }
        category: eventType {
            ... on eventType_Category {
                id
                title
            }
        }
    }

    exhibition: entry(section: "exhibition", slug: $slug) {
        title
        summary
        sectionHandle
        startDate
            @formatDateTime(
                format: "Y-m-d\\TH:i"
                timezone: "America/Los_Angeles"
            )
        endDate
            @formatDateTime(
                format: "Y-m-d\\TH:i"
                timezone: "America/Los_Angeles"
            )
        ongoing
        image: heroImage {
            ... on heroImage_heroImage_BlockType {
                image {
                    ...Image
                }
                altText
            }
        }
        ... on exhibition_exhibition_Entry {
            sectionHandle
            typeHandle
            uri
            slug
            associatedLocationsAndPrograms {
                title
                to: uri
            }
            buttonUrl {
                ... on buttonUrl_button_BlockType {
                    buttonText
                    buttonUrl
                }
            }
            exhibitsAndEvents {
                title
                uri
                sectionHandle
                startDateWithTime
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                endDateWithTime
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                image: heroImage {
                    ... on heroImage_heroImage_BlockType {
                        image {
                            ...Image
                        }
                    }
                }
                text: eventDescription
                locations: associatedLocations {
                    ... on location_location_Entry {
                        id
                        to: uri
                        title
                        summary
                    }
                }
                category: eventType {
                    ... on eventType_Category {
                        id
                        title
                    }
                }
            }
            associatedStaffMember {
                email
                phoneNumber
                staffMemberJobTitle
                nameFirst
                nameLast
                uri
                bookAConsultation
                staffDepartment {
                    title
                }
                image: staffPortrait {
                    ...Image
                }
            }
            acknowledgements {
                ... on acknowledgements_richTextWithSectionTitle_BlockType {
                    displaySectionTitle
                    titleGeneral
                    acknowledgements
                }
            }
            ...ExhibitionsAndCollectionsFpb
        }
    }
}
