#import "~/gql/fragments/Image"

query EventsExhibitionsList {
    entry(section: "listingEventsExhibitions") {
        ... on listingEventsExhibitions_listingEventsExhibitions_Entry {
            title
            text: summary
            featuredEvents {
                category
                title
                summary
                sectionHandle
                to: uri
                eventType {
                    title
                }
                eventDescription
                startDate
                    @formatDateTime(
                        format: "Y-m-d\\TH:i:s"
                        timezone: "America/Los_Angeles"
                    )
                endDate
                    @formatDateTime(
                        format: "Y-m-d\\TH:i:s"
                        timezone: "America/Los_Angeles"
                    )
                startDateWithTime
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                endDateWithTime
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                workshopOrEventSeriesType
                typeHandle
                associatedLocations {
                    title
                    to: uri
                }
                associatedLocationsAndPrograms {
                    title
                    to: uri
                }
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                    }
                }
            }
        }
    }
    events: entries(
        section: "event"
        orderBy: "startDateWithTime ASC"
        startDateWithTime: ">= now"
        limit: 10
    ) {
        title
        to: uri
        sectionHandle
        eventType {
            title
        }
        startDateWithTime
            @formatDateTime(
                format: "Y-m-d\\TH:i:s"
                timezone: "America/Los_Angeles"
            )
        endDateWithTime
            @formatDateTime(
                format: "Y-m-d\\TH:i:s"
                timezone: "America/Los_Angeles"
            )
        associatedLocations {
            title
        }
        eventLocation {
            title
        }
        # Request for heroImage results in 503 error if not limited to 10 entries
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
            }
        }
    }
    series: entries(
        section: "workshopOrEventSeries"
        workshopOrEventSeriesType: "visit/events-exhibitions"
        orderBy: "title"
    ) {
        title
        sectionHandle
        text: summary
        to: uri
        category: workshopOrEventSeriesType
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
            }
        }
    }
    exhibitions: entries(section: "exhibition", orderBy: "title") {
        title
        typeHandle
        sectionHandle
        text: summary
        to: uri
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
            }
        }
    }
}
