#import "~/gql/fragments/Image"

query EventsExhibitionsList {
  entry(section: "listingEventsExhibitions") {
    ... on listingEventsExhibitions_listingEventsExhibitions_Entry {
      title
      summary
      featuredEvents {
        title
        summary
        uri
        eventType
        eventDescription
        seriesDate {
          startDate @formatDateTime(format: "M j", timezone: "America/Los_Angeles")
          endDate @formatDateTime(format: "M j, Y", timezone: "America/Los_Angeles")
        }
        date {
          startDate: startTime @formatDateTime(format: "M j, Y", timezone: "America/Los_Angeles")
          startTime @formatDateTime(format: "h:i a", timezone: "America/Los_Angeles")
          endTime @formatDateTime(format: "h:i a", timezone: "America/Los_Angeles")
        }
        workshopOrEventSeriesType
        associatedLocations {
          title
        }
        heroImage {
          ... on heroImage_heroImage_BlockType {
            id
            image {
              ...Image
            }
            altText
          }
        }
      }
    }
  }
  events: entries(section: "event") {
    title
    summary
    uri
    eventDescription
    eventType
    seriesDate {
      startDate @formatDateTime(format: "M j", timezone: "America/Los_Angeles")
      endDate @formatDateTime(format: "M j, Y", timezone: "America/Los_Angeles")
    }
    date {
      startMonth: startTime @formatDateTime(format: "M", timezone: "America/Los_Angeles")
      startDate: startTime @formatDateTime(format: "j", timezone: "America/Los_Angeles")
      startDateLong: startTime @formatDateTime(format: "l, M j, Y", timezone: "America/Los_Angeles")
      startTime @formatDateTime(format: "h:i a", timezone: "America/Los_Angeles")
    }
    workshopOrEventSeriesType
    associatedLocations {
      title
    }
    heroImage {
      ... on heroImage_heroImage_BlockType {
        id
        image {
          ...Image
        }
        altText
      }
    }
  }
} 
