query Globals {
    globalSets {
        ... on siteSettings_GlobalSet {
            appointmentsLink: externalUrl {
                urlText
                theUrl
            }
        }
        ... on askALibrarian_GlobalSet {
            askALibrarianId: id
            askALibrarianTitle: titleGeneral
            askALibrarianText: summary
            askALibrarianButtonUrl: buttonUrl {
                buttonText
                buttonUrl
            }
        }
    }
}
