query Globals {
    globalSets {
    ... on siteSettings_GlobalSet {
      appointmentsLink: externalUrl {
        ... on externalUrl_urlBlock_BlockType {
          urlText
          theUrl
        }
      }
    }
  }
}
