query Globals {
    globalSets {
        ... on askALibrarian_GlobalSet {
            id
            askALibrarianTitle: titleGeneral
            askALibrarianText: summary
            buttonUrl {
                buttonText
                buttonUrl
            }
        }
        ... on meapCallToAction_GlobalSet {
            id
            name
            titleGeneral
            summary
            button: buttonUrl {
                buttonText
                buttonUrl
            }
        }
    }
}
