#import "../gql/fragments/MenuItem.gql"

query HeaderMainMenuItems {
    secondary: nodes(navHandle: "secondaryMenu", level: 1) {
        ...MenuItem
    }
    primary: nodes(navHandle: "primaryMenu", level: 1) {
        ...MenuItem
        children {
            ...MenuItem
        }
    }
}
