#import "~/gql/fragments/collections/MEAPDefaultFpb"

query HelpTopicDetail($slug: [String!]) {
    entry(section: "meapHelpTopic", slug: $slug) {
        id
        title
        summary
        richText
        helpTopicBlocks: meapHelpTopicBlock {
            id
            sectionTitle
            sectionSummary
            associatedEntries {
                to: uri
                title
                text: summary
            }
        }
        ...MEAPDefaultFpb
    }
}
