query HelpTopicList {
    entries(section: "helpTopic") {
        ... on helpTopic_helpTopic_Entry {
            id
            to: uri
            title
            text: summary
            typeHandle
        }
    }
}
