#import "../gql/fragments/collections/DefaultFpb.gql"

query HelpTopicDetail($slug: [String!]) {
    entry(section: "helpTopic", slug: $slug) {
        id
        title
        text: summary
        richText
        sectionHandle
        slug
        uri
        helpTopicBlocks: helpTopicBlock {
            id
            sectionTitle
            sectionSummary
            associatedEntries {
                uri
                externalResourceUrl
                title
                text: summary
            }
        }
        ...DefaultFpb
    }
}
