#import "../gql/fragments/Image.gql"

query Homepage {
    entry(section: "homepage") {
        title
        summary
        ... on homepage_homepage_Entry {
            searchLinks {
                ... on searchLinks_searchLinks_BlockType {
                    text: searchLinkText
                    url: searchLinkUrl
                }
            }
            getHelpWith {
                ... on getHelpWith_getHelpWith_BlockType {
                    titleGeneral
                    sectionSummary
                    getHelpWith {
                        title
                        text: summary
                        uri
                        externalResourceUrl
                        iconName: illustrationsResourcesAndServices
                    }
                }
            }
            featuredEvents {
                id
                sectionHandle
                uri
                workshopOrEventSeriesType
                title
                eventTitle
                startDateWithTime
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                endDateWithTime
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                category: eventType {
                    ... on eventType_Category {
                        id
                        title
                    }
                }
                eventDescription
                summary
                startDate
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                endDate
                    @formatDateTime(
                        format: "Y-m-d\\TH:i"
                        timezone: "America/Los_Angeles"
                    )
                associatedLocations {
                    ... on location_location_Entry {
                        id
                        to: uri
                        title
                        summary
                    }
                }
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                        altText
                    }
                }
            }
            featuredCollections {
                id
                sectionHandle
                title
                text: summary
                uri
                category: physicalDigital
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                        altText
                    }
                }
                buttonUrl {
                    ... on buttonUrl_button_BlockType {
                        buttonText
                        buttonUrl
                    }
                }
            }
            featuredNews {
                id
                sectionHandle
                title
                text: summary
                to: uri
                externalResourceUrl
                postDate
                articleCategories {
                    title
                }
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                        altText
                    }
                }
            }
        }
    }
}
