#import "../gql/fragments/Image.gql"

query ImpactReportsList {
  entry(section: "listingImpactReports") {
    ... on listingImpactReports_listingImpactReports_Entry {
      title
      summary
    }
  }
  entries(section: "impactReport", orderBy: "postDate desc") {
    ... on impactReport_impactReport_Entry {
      title
      to: uri
      richText
      image {
          ...Image
      }
    }
  }
}