#import "~/gql/fragments/collections/AllFpb"

query ImpactReportStory($slug: [String!]) {
  entry(section: "impactReportStory", uri: $slug) {
    ... on impactReportStory_impactReportStory_Entry {
      id
      title
      text: summary
      heroImage {
        ... on heroImage_heroImage_BlockType {
          id
          image {
            ... on mediaAndDocuments_Asset {
              id
              altText
              title
            }
          }
        }
      }
      contributor
      to: uri
      ...AllFpb
    }
  }
}

# query ImpactReportStory {
#  entry(section: "impactReportStory", uri: "impact/2022/test-main-story") {
