query ImpactReportStory($slug: [String!]) {
    entry(section: "impactReportStory", uri: $slug) {
        ... on impactReportStory_impactReportStory_Entry {
        id
        title
        to: uri
        }
  }
}
