query JobOpportunitiesList {
  entry(section: "listingCareers", orderBy: "postDate") {
    ... on listingCareers_listingCareers_Entry {
      title
      text: summary
      email
      phoneNumber
      associatedTopics {
        title
        text: summary
        to: uri
        externalResourceUrl
        illustrationsResourcesAndServices
      }
    }
  }
  allJobs: entries(section: "job", staffOrStudentPosition: "careers") {
    title
    text: summary
    ... on job_job_Entry {
      jobType {
        ... on jobType_Category {
          title
        }
      }
      jobRequisitionNumber
      jobPostingURL
      department {
        title
      }
      associatedLocations {
        title
        uri
      }
    }
  }
}
