query CareersList {
  entry(section: "listingCareers", orderBy: "postDate") {
    ... on listingCareers_listingCareers_Entry {
      title
      text: summary
      email
      phoneNumber
      associatedTopics {
        title
        text: summary
        uri
        externalResourceUrl
        illustrationsResourcesAndServices
      }
    }
  }
  entries(section: "job", staffOrStudentPosition: "careers") {
    title
    summary
    ... on job_job_Entry {
      jobType {
        ... on jobType_Category {
          title
        }
      }
      jobRequisitionNumber
      jobPostingURL
      department {
        title
      }
      associatedLocations: location {
        title
        uri: publicUrl
      }
    }
  }
}
