#import "~/gql/fragments/Image"
query LocationsList {
  entry(section: "listingLocationsHours") {
    title
    summary
  }
  entries(section: "location") {
    locationType
    campusMapId
    libcalLocationIdForHours
    libcalSpacesUrl
    title
    summary
    heroImage {
      ... on heroImage_heroImage_BlockType {
        id
        image {
          ...Image
        }
      }
    }
    address {
      ... on address_addressFields_BlockType {
        addressLine1
        addressLine2
        addressCity
        addressState
        addressZipCode
      }
    }
    amenities(label: true)
    amenitiesIcons: amenities(label: false)
    uri
    affiliateLibraryUrl
  }
}
