#import "~/gql/fragments/Image"
query LocationsList {
    entries(section: "location") {
        ... on location_location_Entry {
            id
            locationType
            to: slug
            title
            address {
                id
                addressLine1
                addressLine2
                addressCity
                addressState
                addressZipCode
                addressCountry
            }
            amenities(label: true)
            heroImage {
                image {
                    ...Image
                }
            }
        }
    }
    entry(section: "listingLocationsHours") {
        ... on listingLocationsHours_listingLocationsHours_Entry {
            id
            locationHoursListTitle: titleGeneral
            locationHoursListSummary: summary
            featuredNewsListing {
                id
                title
                text: summary
                uri
                externalResourceUrl
            }
        }
    }
}
