#import "~/gql/fragments/Image"
query LocationDetail($slug: [String!]) {
    entry(section: "location", slug: $slug) {
        ... on location_location_Entry {
            id
            locationType
            title
            heroImage {
                image {
                    ...Image
                }
            }
            summary
            email
            phoneNumber
            address {
                id
                addressLine1
                addressLine2
                addressCity
                addressState
                addressZipCode
                addressCountry
            }
            howToGetHere
            amenities(label: true)
            space {
                title
                summary
                mediatedBooking
                mediatorEmail
                reservationUrl
                spaceType {
                    id
                    title
                }
                spaceAmenities {
                    id
                    title
                }
                associatedLocations {
                    id
                    to: slug
                    title
                }
            }
            resourceServiceWorkshop {
                id
                text: summary
                title
                slug
                uri
                researchGuideUrl
                type: serviceOrResourceType
            }
            campusMapId
            libcalLocationIdForHours

            staffMember {
                id
                email
                to: uri
            }
            exhibitsAndEvents(orderBy: "dateUpdated desc", limit: 3) {
                id
                uri
                title
                summary
                dateUpdated
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                    }
                }
                date {
                    startDate
                    endDate
                }
                seriesDate {
                    startDate
                    endDate
                }
                associatedLocations {
                    id
                    title
                    to: uri
                }
            }
            endowment(orderBy: "dateUpdated desc", limit: 3) {
                id
                uri
                title
                summary
                dateUpdated
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                    }
                }
            }
            associatedArticles(orderBy: "dateUpdated desc", limit: 3) {
                id
                uri
                slug
                title
                summary
                articleType
                author: staffMember {
                    id
                    slug
                    title
                }
                articleType
                startDate: dateUpdated
                endDate: dateUpdated
                associatedLocations {
                    id
                    title
                }
                heroImage {
                    ... on heroImage_heroImage_BlockType {
                        id
                        image {
                            ...Image
                        }
                    }
                }
            }
            ...FlexibleBlocksLocation
        }
    }
}

fragment FlexibleBlocksLocation on ElementInterface {
    blocks: defaultFpb {
        id
        typeHandle
        ...BlockDivider
        ...BlockPullQuote
        ...BlockRichText
        ...BlockMediaWithText
        ...BlockSimpleCards
        ...BlockCallToAction
    }
}

fragment BlockRichText on defaultFpb_richText_BlockType {
    richText
}

fragment BlockPullQuote on defaultFpb_pullQuote_BlockType {
    id
    pullQuote {
        ... on pullQuote_pullQuote_BlockType {
            text
            attribution
        }
    }
}

fragment BlockDivider on defaultFpb_divider_BlockType {
    id
    divider
}

fragment BlockMediaWithText on defaultFpb_mediaWithText_BlockType {
    id
    sectionTitle: titleGeneral
    sectionSummary: summary
    mediaWithText {
        ... on mediaWithText_mediaLink_BlockType {
            id
            titleLink
            description
            coverImage {
                ...Image
            }
            buttonText
            buttonUrl
            linkToMedia
            typeMedia
        }
        ... on mediaWithText_mediaUpload_BlockType {
            id
            titleUpload
            description
            buttonText
            buttonUrl
            coverImage {
                ...Image
            }
            upload {
                ...Image
            }
            typeMedia
        }
    }
}

fragment BlockSimpleCards on defaultFpb_simpleCards_BlockType {
    id
    sectionTitle: titleGeneral
    sectionSummary: summary
    cards: simpleCards {
        ... on simpleCards_internalServiceOrResource_BlockType {
            id
            title: titleGeneral
            summary
            contentLink {
                slug
                title
                summary
                researchGuideUrl
            }
        }
        ... on simpleCards_externalServiceOrResource_BlockType {
            id
            title: titleGeneral
            summary
            externalLink
        }
    }
}

fragment BlockCallToAction on defaultFpb_callToAction_BlockType {
    id
    callToAction {
        ... on callToAction_callToAction_BlockType {
            id
            titleCta
            summary
            icon
            buttonText
            buttonLink
            backgroundColor
        }
    }
}
