#import "~/gql/fragments/collections/DefaultFpb"
#import "~/gql/fragments/Image"

query LocationDetail($slug: [String!]) {
    entry(section: "location", slug: $slug) {
        ... on location_location_Entry {
            id
            locationType
            title
            richTextSimplified
            heroImage {
                image {
                    ...Image
                }
            }
            summary
            email
            phoneNumber
            address {
                id
                addressLine1
                addressLine2
                addressCity
                addressState
                addressZipCode
                addressCountry
            }
            howToGetHere
            amenities(label: true)
            space {
                title
                text: summary
                reservationRequired
                mediatorEmail
                reservationUrl
                spaceType {
                    id
                    title
                }
                spaceAmenities {
                    id
                    title
                }
                associatedLocations {
                    id
                    to: slug
                    title
                }
            }
            resourceServiceWorkshop {
                id
                text: summary
                title
                slug
                uri
                externalResourceUrl
                type: serviceOrResourceType
            }
            campusMapId
            libcalLocationIdForHours
            staffMember {
                id
                email
                to: uri
            }
            ...DefaultFpb
        }
    }
    associatedArticles: entries(
        section: "article"
        relatedToEntries: { section: "location", slug: $slug }
        orderBy: "dateUpdated desc"
        limit: 3
    ) {
        ... on article_article_Entry {
            id
            title
            articleType
            associatedLocations {
                id
                title
            }
            to: slug
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                    altText
                }
            }

            authors: staffMember {
                id
                slug
                title
            }
            description: summary
            category: typeHandle
            startDate: dateUpdated
            endDate: dateUpdated
        }
    }
    associatedEndowments: entries(
        section: "endowments"
        relatedToEntries: { section: "location", slug: $slug }
    ) {
        ... on endowment_endowments_Entry {
            id
            slug
            title
            summary
            dateUpdated
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }
        }
    }
    associatedEvents: entries(
        section: "event"
        relatedToEntries: { section: "location", slug: $slug }
    ) {
        ... on event_event_Entry {
            id
            slug
            title
            date {
                startTime
                endTime
            }
            associatedLocations {
                id
                title
                to: uri
            }
            requiresRegistration
            eventDescription
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }
            eventType
            eventLocation
            isOnline: onlineEventUrl
            moreInformation
            eventOwner
        }
    }
    associatedExhibitions: entries(
        section: "exhibition"
        relatedToEntries: { section: "location", slug: $slug }
    ) {
        ... on exhibition_exhibition_Entry {
            id
            title
            id
            uri
            title
            summary
            dateUpdated
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }
            date {
                startDate
                endDate
            }
            seriesDate {
                startDate
                endDate
            }
            associatedLocations {
                id
                title
                to: uri
            }
        }
    }
}
