query PoliciesList {
  entries(section: "policy") {
    ... on policy_policy_Entry {
      id
      to: slug
      title
      summary
    }
  }
  entry(section: "listingPolicies") {
    ... on listingPolicies_listingPolicies_Entry {
      libraryPoliciesListTitle: titleGeneral
      libraryPoliciesListSummary: summary
      policyBlock {
        ... on policyBlock_policyBlock_BlockType {
          id
          sectionSummary
          sectionTitle
        }
      }
    }
  }
}
