#import "~/gql/fragments/collections/AllFpbWithNoBanner"

query PoliciesList {
  entry(section: "listingPolicies") {
    ... on listingPolicies_listingPolicies_Entry {
      title
      summary
      policyBlock {
        sectionSummary
        sectionTitle
        associatedEntries {
          to: uri
          title
          text: summary
        }
      }
      ...AllFpbWithNoBanner
    }
  }
}
