#import "~/gql/fragments/Image"
#import "~/gql/fragments/collections/AllFpb"

query PolicyDetail($slug: [String!]) {
    entry(section: "policy", slug: $slug) {
        id
        sectionHandle
        slug
        uri
        title
        summary
        richText
        to: uri
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
            }
        }
        ...AllFpb
    }
}
