#import "../gql/fragments/Image.gql"
#import "../gql/fragments/collections/AllFpb.gql"

query PolicyDetail($slug: [String!]) {
    entry(section: "policy", slug: $slug) {
        id
        sectionHandle
        slug
        uri
        title
        text: summary
        richText
        to: uri
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
            }
        }
        ...AllFpb
    }
}
