#import "~/gql/fragments/Image"

query ProgramList {
    entry(section: "listingPrograms") {
        ... on listingPrograms_listingPrograms_Entry {
            title
            text: summary
            ... on listingPrograms_listingPrograms_Entry {
                featuredPrograms {
                    ... on program_program_Entry {
                        id
                        title
                        summary
                        uri
                        heroImage {
                            ... on heroImage_heroImage_BlockType {
                                id
                                image {
                                    ...Image
                                }
                            }
                        }
                        buttonUrl {
                            ... on buttonUrl_button_BlockType {
                                id
                                buttonText
                                buttonUrl
                            }
                        }
                        programType {
                            title
                        }
                    }
                }
            }
        }
    }
    entries(section: "program", orderBy: "title ASC") {
        ... on program_program_Entry {
            sectionHandle
            title
            text: summary
            uri
            programUrlBehavior
            buttonUrl {
                ... on buttonUrl_button_BlockType {
                    buttonText
                    buttonUrl
                }
            }
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                }
            }
            programType {
                id
                title
            }
        }
    }
}
