#import "~/gql/fragments/Image"
#import "~/gql/fragments/collections/AllFpb"

query ProgramDetail($slug: [String!]) {
    entry(section: "program", slug: $slug) {
        id
        slug
        uri
        title
        text: summary
        heroImage {
            ... on heroImage_heroImage_BlockType {
                id
                image {
                    ...Image
                }
            }
        }
        buttonUrl {
            ... on buttonUrl_button_BlockType {
                buttonText
                buttonUrl
            }
        }
        email
        phoneNumber
        viewStaffDirectory
        department {
            id
            title
        }
        ...AllFpb
    }
}
