query ProjectList {

    entry(section: "meapListingProjects") {
        ... on meapListingProjects_meapListingProjects_Entry {
            meapID: id
            projectListTitle: titleGeneral
            projectListSummary: summary
            featuredMeapResourcesListing {
                id
                title
                text: summary
                uri
                externalResourceUrl
            }
        }
    }
}
