#import "~/gql/fragments/FlexibleBlocks"
#import "~/gql/fragments/Image"
query ResourceDetail($slug: [String!]) {
  entry(section: "resource", slug: $slug) {
    ... on resource_resource_Entry {
      id
      shortDescription
      title
      button: buttonUrl {
        ... on buttonUrl_button_BlockType {
          id
          buttonText
          buttonUrl
        }
      }
      illustrationsResourcesAndServices
      heroImage {
        ... on heroImage_heroImage_BlockType {
          id
          image {
            ...Image
          }
          altText
        }
      }
      externalUrl {
        ... on externalUrl_urlBlock_BlockType {
          id
          theUrl
          urlText
        }
      }
      locations: associatedLocations {
        id
        to: slug
        title
      }
      helpTopic {
        id
        ... on helpTopic_helpTopic_Entry {
          id
          text: shortDescription
          title
          helpTopicBlock {
            ... on helpTopicBlock_subheader_BlockType {
              id
              subheader
              subheaderShortDescription
              associatedServicesResourcesAndWorkshops {
                ... on service_service_Entry {
                  id
                  title
                  text: shortDescription
                  iconName: illustrationsResourcesAndServices
                }
                ... on resource_resource_Entry {
                  id
                  iconName: illustrationsResourcesAndServices
                  title
                  text: shortDescription
                }
              }
            }
          }
        }
      }
    }
    ...FlexibleBlocks
    typeHandle
  }
}
