#import "~/gql/fragments/FlexibleBlocks"
#import "~/gql/fragments/Image"
query ServiceOrResourceDetail($slug: [String!]){
  entry(section: "serviceOrResource", slug: "sample-service-page-with-faqs") {
    ... on serviceOrResource_serviceOrResource_Entry {
      id
      button: buttonUrl {
        ... on buttonUrl_button_BlockType {
          id
          buttonText
          buttonUrl
        }
      }
      illustrationsResourcesAndServices
      heroImage {
        ... on heroImage_heroImage_BlockType {
          id
          image {
            ...Image
          }
          altText
        }
      }
      serviceOrResourceType
      title
      text: shortDescription
      locations: associatedLocations {
        id
        to: slug
        title
      }
      resourceServiceWorkshop {
        ... on workshop_workshop_Entry {
          id
          text: shortDescription
          title
          to: slug
        }
        ... on helpTopic_helpTopic_Entry {
          id
          helpTopicBlock {
            ... on helpTopicBlock_subheader_BlockType {
              id
              subheader
              subheaderShortDescription
              title
              associatedServicesResourcesAndWorkshops {
                ... on workshop_workshop_Entry {
                  id
                  text: shortDescription
                  title
                  to: slug
                }
                ... on serviceOrResource_serviceOrResource_Entry {
                  id
                  illustrationsResourcesAndServices
                  to: slug
                  title
                  text: shortDescription
                }
              }
            }
          }
        }
        ... on serviceOrResource_serviceOrResource_Entry {
          id
          to: slug
          text: shortDescription
          serviceOrResourceType
          title
        }
        ... on researchGuide_default_Entry {
          id
          researchGuide {
            ... on researchGuide_researchGuide_BlockType {
              id
              researchGuideTitle
              to: researchGuideURL
              text: shortDescription
            }
          }
        }
      }
    }
    ...FlexibleBlocks
  }
}
