query ServiceResourceWorkshopSeriesList {
  serviceOrResource: entries(section: "serviceOrResource") {
    ... on serviceOrResource_serviceOrResource_Entry {
      id
      to: uri
      title
      text: summary
      category: serviceOrResourceType
      iconName: illustrationsResourcesAndServices
    }
  }
  workshopseries: entries(
    section: "workshopOrEventSeries"
    workshopOrEventSeriesType: "help/services-resources"
  ) {
    ... on workshopOrEventSeries_workshopOrEventSeries_Entry {
      id
      to: uri
      title
      text: summary
      category: workshopOrEventSeriesType
    }
  }
}
