#import "~/gql/fragments/Image"
query ServiceOrResourceDetail($slug: [String!]) {
    entry(section: "serviceOrResource", slug: $slug) {
        ... on serviceOrResource_serviceOrResource_Entry {
            id
            button: buttonUrl {
                ... on buttonUrl_button_BlockType {
                    id
                    buttonText
                    buttonUrl
                }
            }
            illustrationsResourcesAndServices
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                    altText
                }
            }
            type: serviceOrResourceType
            title
            text: summary
            locations: associatedLocations {
                id
                to: slug
                title
            }
            associatedTopics {
                id
                text: summary
                title
                slug
                uri
                researchGuideUrl
            }
        }
        ...FlexibleBlocksServiceOrResource
    }
}

fragment FlexibleBlocksServiceOrResource on ElementInterface {
    blocks: defaultFpbWithNoCta {
        id
        typeHandle
        ...BlockDivider
        ...BlockMediaGallery
        ...BlockPullQuote
        ...BlockSimpleCards
        ...BlockRichText
        ...BlockMediaWithText
    }
}

fragment BlockRichText on defaultFpbWithNoCta_richText_BlockType {
    richText
}

fragment BlockPullQuote on defaultFpbWithNoCta_pullQuote_BlockType {
    id
    pullQuote {
        ... on pullQuote_pullQuote_BlockType {
            text
            attribution
        }
    }
}

fragment BlockDivider on defaultFpbWithNoCta_divider_BlockType {
    id
    divider
}

fragment BlockMediaGallery on defaultFpbWithNoCta_mediaGallery_BlockType {
    id
    titleGeneral
    mediaGallery {
        id
        ... on mediaGallery_image_BlockType {
          id
          # ...Image
          # image { id url }

          captionTitle: captionHeading
          captionText: caption
          altText
          sortOrder
          image: imageFile(altText: "") {
                id
                img
                title
                ... on mediaAndDocuments_Asset {
                    id
                    title
                    kind
                    width
                    src: url
                    height
                }
            }
        }
    }
}

fragment BlockSimpleCards on defaultFpbWithNoCta_simpleCards_BlockType {
  id
  sectionTitle: titleGeneral
  sectionSummary: summary
  cards: simpleCards {
    ... on simpleCards_internalServiceOrResource_BlockType {
        id
        title: titleGeneral
        summary
        contentLink {
            slug
            title
            summary
            researchGuideUrl
        }
    }
    ... on simpleCards_externalServiceOrResource_BlockType {
        id
        title: titleGeneral
        summary
        externalLink
        }
    }
}

fragment BlockMediaWithText on defaultFpbWithNoCta_mediaWithText_BlockType {
    id
    sectionTitle: titleGeneral
    sectionSummary: summary
    mediaWithText {
        ... on mediaWithText_mediaLink_BlockType {
            id
            titleLink
            description
            coverImage {
                ...Image
            }
            buttonText
            buttonUrl
            linkToMedia
            typeMedia
        }
        ... on mediaWithText_mediaUpload_BlockType {
            id
            titleUpload
            description
            buttonText
            buttonUrl
            coverImage {
                ...Image
            }
            upload {
                ...Image
            }
            typeMedia
        }
    }
}