#import "~/gql/fragments/collections/DefaultFpbWithNoCta"
#import "~/gql/fragments/collections/DefaultFpbWithCardsAndHighlight"

query ServiceOrResourceOrWorkshopDetail($slug: [String!]) {
    serviceOrResource: entry(section: "serviceOrResource", slug: $slug) {
        ... on serviceOrResource_serviceOrResource_Entry {
            id
            sectionHandle
            slug
            uri
            button: buttonUrl {
                ... on buttonUrl_button_BlockType {
                    id
                    buttonText
                    buttonUrl
                }
            }
            illustrationsResourcesAndServices
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                    altText
                }
            }
            type: serviceOrResourceType
            title
            text: summary
            locations: associatedLocations {
                id
                to: slug
                title
            }
            associatedTopics {
                id
                text: summary
                title
                slug
                uri
                externalResourceUrl
            }
        }
        ...DefaultFpbWithNoCta
    }
    workshopSeries: entry(
        section: "workshopOrEventSeries"
        workshopOrEventSeriesType: "help/services-resources"
        slug: $slug
    ) {
        ... on workshopOrEventSeries_workshopOrEventSeries_Entry {
            id
            workshopOrEventSeriesType
            sectionHandle
            typeHandle
            title
            summary
            startDate
                @formatDateTime(
                    format: "Y-m-d\\TH:i"
                    timezone: "America/Los_Angeles"
                )
            endDate
                @formatDateTime(
                    format: "Y-m-d\\TH:i"
                    timezone: "America/Los_Angeles"
                )
        }

        associatedLocations {
            ... on location_location_Entry {
                id
                to: uri
                title
                summary
            }
        }
        image: heroImage {
            ... on heroImage_heroImage_BlockType {
                image {
                    ...Image
                }
            }
        }
        event {
            id
            title
            uri
            sectionHandle
            text: eventDescription
            category: eventType {
                ... on eventType_Category {
                    id
                    title
                }
            }
            image: heroImage {
                ... on heroImage_heroImage_BlockType {
                    image {
                        ...Image
                    }
                }
            }
            startDateWithTime
                @formatDateTime(
                    format: "Y-m-d\\TH:i"
                    timezone: "America/Los_Angeles"
                )
            endDateWithTime
                @formatDateTime(
                    format: "Y-m-d\\TH:i"
                    timezone: "America/Los_Angeles"
                )
            locations: associatedLocations {
                ... on location_location_Entry {
                    id
                    to: uri
                    title
                    summary
                }
            }
        }
        associatedTopics {
            id
            title
            text: summary
            to: uri
            illustration
        }
        ...DefaultFpbWithCardsAndHighlight
    }

    pastEvents: entries(
    section: "event"
    orderBy: "startDateWithTime DESC"
    startDateWithTime: "< now"
    relatedToEntries: {section: "workshopOrEventSeries", slug: $slug}
  ) {
    title
    to: uri
    sectionHandle
    eventType {
      title
    }
    startDateWithTime @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
    endDateWithTime @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
    associatedLocations {
      title
    }
    eventLocation {
      title
    }
    image: heroImage {
                    ... on heroImage_heroImage_BlockType {
                        image {
                            ...Image
                        }
                    }
                }
  }

  upcomingEvents: entries(
    section: "event"
    orderBy: "startDateWithTime ASC"
    startDateWithTime: ">= now"
    relatedToEntries: {section: "workshopOrEventSeries", slug: $slug}
  ) {
    title
    to: uri
    sectionHandle
    eventType {
      title
    }
    startDateWithTime @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
    endDateWithTime @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
    associatedLocations {
      title
    }
    eventLocation {
      title
    }
    image: heroImage {
                    ... on heroImage_heroImage_BlockType {
                        image {
                            ...Image
                        }
                    }
                }
  }
  
    associatedSeries: entries(
        section: "workshopOrEventSeries"
        relatedToEntries: { section: "workshopOrEventSeries", slug: $slug }
    ) {
        title
        sectionHandle
        text: summary
        image: heroImage {
            ... on heroImage_heroImage_BlockType {
                image {
                    ...Image
                }
            }
        }
        to: uri
        startDate
            @formatDateTime(
                format: "Y-m-d\\TH:i"
                timezone: "America/Los_Angeles"
            )
        endDate
            @formatDateTime(
                format: "Y-m-d\\TH:i"
                timezone: "America/Los_Angeles"
            )
    }
}
