#import "~/gql/fragments/DefaultFpbWithNoCta"
#import "~/gql/fragments/Image"
#import "~/gql/fragments/BlockDividerFragment"

#import "~/gql/fragments/BlockMediaWithTextFragment"
#import "~/gql/fragments/BlockPullQuoteFragment"
#import "~/gql/fragments/BlockRichTextFragment"
#import "~/gql/fragments/BlockSimpleCardsFragment"

query ServiceOrResourceDetail($slug: [String!]) {
    entry(section: "serviceOrResource", slug: $slug) {
        ... on serviceOrResource_serviceOrResource_Entry {
            id
            button: buttonUrl {
                ... on buttonUrl_button_BlockType {
                    id
                    buttonText
                    buttonUrl
                }
            }
            illustrationsResourcesAndServices
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                    altText
                }
            }
            type: serviceOrResourceType
            title
            text: summary
            locations: associatedLocations {
                id
                to: slug
                title
            }
            associatedTopics {
                id
                text: summary
                title
                slug
                uri
                researchGuideUrl
            }
        }
        ...DefaultFpbWithNoCta
    }
}
