#import "~/gql/fragments/Image"
query StaffList {
    entries(section: "staffMember", orderBy: "staffMemberJobTitle") {
        ... on staffMember_staffMember_Entry {
            email
            phone: phoneNumber
            jobTitle: staffMemberJobTitle
            nameFirst
            nameLast
            to: slug
            consultation: bookAConsultation
            departments: staffDepartment {
                id
                title
            }
            locations: staffAssociatedLocations {
                id
                title
                to: slug
            }
            image {
                ...Image
            }
        }
    }
}
