#import "~/gql/fragments/Image"
query StaffList {
    entry(section: "listingStaffDirectory") {
        title
        text: summary
    }
    entries(section: "staffMember", orderBy: "nameLast") {
        ... on staffMember_staffMember_Entry {
            jobTitle: staffMemberJobTitle
            nameFirst
            nameLast
            to: slug
            alternativeName {
                ... on alternativeName_alternativeName_BlockType {
                    fullName
                    languageAltName
                }
            }
            email
            phone: phoneNumber
            consultation: bookAConsultation
            departments: staffDepartment(orderBy: "level") {
                id
                title
            }
            locations: staffAssociatedLocations {
                id
                title
                to: slug
            }
            image: staffPortrait {
                ...Image
            }
        }
    }
}
