query StaffMember {
  entries(section: "staffMember") {
    email
    phone: phoneNumber
    jobTitle: staffMemberJobTitle
    staffName: staffMemberName
    to: slug
    dept: department {
      title
    }
  }
}
