#import "~/gql/fragments/Image"
query StaffDetail($slug: [String]!) {
    entry(section: "staffMember", slug: $slug) {
        ... on staffMember_staffMember_Entry {
            id
            title
            image: staffPortrait {
                ...Image
            }
            to: slug
            nameFirst
            nameLast
            jobTitle: staffMemberJobTitle
            departments: staffDepartment(orderBy: "level") {
                id
                title
            }
            locations: staffAssociatedLocations {
                title
                to: uri
                id
            }
            pronouns
            email
            phone: phoneNumber
            consultation: bookAConsultation
            topics: askMeAbout {
                title
                id
            }
            biography
            subjectLibrarian
            orcid: orcidId
            publications
        }
    }
    entries(
        section: "article"
        relatedToEntries: { section: "staffMember", slug: $slug }
    ) {
        ... on article_article_Entry {
            id
            title
            to: slug
            heroImage {
                ... on heroImage_heroImage_BlockType {
                    id
                    image {
                        ...Image
                    }
                    altText
                }
            }

            authors: staffMember {
                id
                slug
                title
            }
            description: summary
            category: typeHandle
            date: dateUpdated
        }
    }
}
