#import "~/gql/fragments/Image"
query StaffMember($slug: [String]!) {
  entry(section: "staffMember", slug: $slug) {
    ... on staffMember_staffMember_Entry {
      email
      phone: phoneNumber
      jobTitle: staffMemberJobTitle
      staffName: staffMemberName
      to: slug
      topics: askMeAbout {
        title
        slug
      }
      biography
      departments: department {
        title
        slug
      }
      locations: associatedLocations {
        title
        to: uri
        slug
      }
      image {
        ...Image
      }
    }
  }
}
