query TutorialCTA {
  entry(section: "listingTutorials") {
    ... on listingTutorials_listingTutorials_Entry {
      callToAction2Up {
        ... on callToAction2Up_callToAction_BlockType {
          title: titleCta
          text: summary
          svgName: icon
          name: buttonText
          to: buttonLink
          backgroundColor
        }
      }
    }
  }
}
