#import "../gql/fragments/Image.gql"
query TutorialsListing {
  entry(section: "listingTutorials") {
    title
    summary
    sectionTitle
    richTextDefault
    featuredResourcesSection {
      ... on featuredResourcesSection_featuredResources_BlockType {
        titleGeneral
        sectionSummary
        featuredResources {
          title
          text: summary
          to: uri
          externalResourceUrl
          tutorialType
          tutorialCategory
          image {
          ...Image
          }
        }
      }
    }
    callToAction2Up {
      ... on callToAction2Up_callToAction_BlockType {
        titleCta
        summary
        icon
        buttonText
        buttonLink
        backgroundColor
      }
    }
  }
  entries(
    section: "tutorial"
    orderBy: "title ASC"
    ) {
    ... on tutorial_tutorial_Entry {
      title
      summary
      uri
      image {
        ...Image
      }
      typeHandle
      tutorialType {
        id
        title
      }
      tutorialCategory {
        id
        title
      }
    }
  }
}
