#import "../gql/fragments/Image.gql"
#import "../gql/fragments/collections/AllFpb.gql"

query TutorialDetail($slug: [String!]) {
  entry(section: "tutorial", slug: $slug) {
    id
    slug
    uri
    typeHandle
    sectionHandle
    title
    summary
    buttonText
    buttonUrl {
        ... on buttonUrl_button_BlockType {
            buttonText
            buttonUrl
        }
    }
    heroImage {
      image
    }
    tutorialType {
      title
    }
    tutorialCategory {
      title
    }
    learningOutcomes: richTextDefault
    ...AllFpb

    resourceServiceWorkshop {
      ... on collection_collection_Entry {
        title
        text: summary
        slug
        uri
      }
      ... on endowment_endowments_Entry {
        title
        text: summary
        slug
        uri
      }
      ... on externalResource_externalResource_Entry {
        title
        text: summary
        slug
        externalResourceUrl
      }
      ... on generalContentPage_generalContentPage_Entry {
        title
        text: summary
        slug
        uri
      }
      ... on helpTopic_helpTopic_Entry {
        title
        text: summary
        slug
        uri
      }
      ... on serviceOrResource_serviceOrResource_Entry {
        title
        text: summary
        slug
        uri
      }
      ... on tutorial_tutorial_Entry {
        title
        text: summary
        slug
        uri
      }
      ... on workshopOrEventSeries_workshopOrEventSeries_Entry {
        title
        text: summary
        slug
        uri
      }
    }

    awardsAndRecognition {
      text
      uri
      heroImage {
          ... on heroImage_heroImage_BlockType {
              id
              image {
                  ...Image
              }
          }
      }
    }
    authors {
      ... on authors_staffMember_BlockType {
        staffMember {
          title
        }
      }
      ... on authors_externalContributor_BlockType {
        contributor
      }
    }
    contributorsNoMax {
      ... on contributorsNoMax_staffMember_BlockType {
        staffMember {
          title
        }
      }
      ... on contributorsNoMax_externalContributor_BlockType {
        contributor
      }
    }
  }
}
