name: Build prod site daily and on release

# Performs a Website release using Netlify daily, and when a new GitHub release has been published
on:
  release:
    types: [ published ]
  schedule:
    - cron:  '00 9 * * *' # 9am UTC = 2am PDT, 1am PST

jobs:
  nuxt-prod:
    name: Netlify deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v3
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
    - run: gh workflow run build-and-deploy --ref ${{ steps.previoustag.outputs.tag }} --field environment=prod
