
name: Run CI Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: ./.github/workflows/setup-workspace
    - run: npm run lint

  percy-instructions:
    runs-on: ubuntu-latest
    steps:
      - name: Comment with percy instructions
        uses: bubkoo/auto-comment@c907eece18ad79480d1058c2577e63fb5b5f1604
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            # Percy Screenshots

            In order to conserve our percy screenshot allowance, percy is not configured to run automatically. Please make sure the PR is ready and all other checks are passing, then start it manually:
            1. Visit https://github.com/UCLALibrary/library-website-nuxt/actions/workflows/percy.yml
            2. Click the 'Run workflow' button in the blue bar. 
            3. Select the correct branch for this PR and click 'Run workflow' again to confirm.

  storybook:
    env:
      GITHUB_ENV_NAME: ${{ github.event_name }}-${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: ./.github/workflows/setup-workspace
    - run: npx nuxt storybook build --output-dir ./storybook-static
    - run: echo "GITHUB_ENV_NAME=production" >> $GITHUB_ENV
      if: github.head_ref=='main'
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@f517512ae75beec8896aa7b027c1c72f01816200
      with:
        production-branch: main
        production-deploy: ${{ github.event_name=='push' && github.head_ref=='main' }}
        alias: ${{ env.GITHUB_ENV_NAME }}
        deploy-message: "Deploy from GitHub Actions"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        overwrites-pull-request-comment: true
        publish-dir: './storybook-static'
        fails-without-credentials: true
        github-deployment-environment: storybook--${{ env.GITHUB_ENV_NAME }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STORYBOOK }}
    - name: Cypress test for Storybook Components
      uses: cypress-io/github-action@2113e5bc19c45979ba123df6e07256d2aaba9a33
      with:
        start: npx http-server ./storybook-static -p 3009
        command-prefix: 'npx'
        config-file: cypress.storybook.json
        wait-on: http://localhost:3009
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_STORYBOOK }}

  nuxt:
    env:
      GITHUB_ENV_NAME: ${{ github.event_name }}-${{ github.event.number }}
    name: Nuxt build / Cypress tests / Netlify deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: ./.github/workflows/setup-workspace
    - name: Cache built static site
      uses: actions/cache@v2
      with:
        path: ./dist
        key: nuxt-site-${{ github.sha }}
    - run: npm run generate
      env:
        CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT }}
        LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
        LIBCAL_CLIENT_SECRET: ${{ secrets.LIBCAL_CLIENT_SECRET }}
        LIBCAL_CLIENT_ID: ${{ secrets.LIBCAL_CLIENT_ID }}
        S3_BUCKET: "https://static.library.ucla.edu/"
    - uses: cypress-io/github-action@2113e5bc19c45979ba123df6e07256d2aaba9a33
      with:
        start: npx http-server ./dist -p 3000
        command-prefix: 'npx'
        wait-on: http://localhost:3000
      env:
        CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT }}
        LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
        LIBCAL_CLIENT_SECRET: ${{ secrets.LIBCAL_CLIENT_SECRET }}
        LIBCAL_CLIENT_ID: ${{ secrets.LIBCAL_CLIENT_ID }}
        S3_BUCKET: "https://static.library.ucla.edu/"
    - run: echo "GITHUB_ENV_NAME=production" >> $GITHUB_ENV
      if: github.head_ref=='main'
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@f517512ae75beec8896aa7b027c1c72f01816200
      with:
        production-branch: main
        production-deploy: ${{ github.event_name=='push' && github.head_ref=='main' }}
        alias: ${{ env.GITHUB_ENV_NAME }}
        deploy-message: "Deploy from GitHub Actions"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        overwrites-pull-request-comment: true
        publish-dir: './dist'
        fails-without-credentials: true
        github-deployment-environment: ${{ env.GITHUB_ENV_NAME }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
