name: Run CI Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  percy-instructions:
    runs-on: ubuntu-latest
    steps:
      - name: Comment with percy instructions
        uses: bubkoo/auto-comment@c907eece18ad79480d1058c2577e63fb5b5f1604
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            # Percy Screenshots

            In order to conserve our percy screenshot allowance, percy is not configured to run automatically. Please make sure the PR is ready and all other checks are passing, then start it manually:
            0. Visit https://github.com/UCLALibrary/library-website-nuxt/actions/workflows/percy.yml
            0. Click the 'Run workflow' button in the blue bar. 
            0. Select the correct branch for this PR and click 'Run workflow' again to confirm.
