
name: Run CI Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref_name=='main' && github.sha || github.ref_name }} # Cancel runs for previous version of PR, but not main (after merge). For hacked ternary, see https://github.com/actions/runner/issues/409#issuecomment-727565588
  cancel-in-progress: true

jobs:
  test-curl-action:
    name: "Perform REST API request"
    runs-on: ubuntu-latest
    steps:
      #- name: "Call API"
       # uses: indiesdev/curl@v1.1
        #with:
         # url: ${{ secrets.ES_URL }}/apps-test-2023-deploy-preview-index?pretty
          #headers: '{ "Content-Type": "application/json", "Authorization": "ApiKey ${{ secrets.ES_WRITE_KEY_TEST }}" }'
          #method: "PUT"
          #log-response: true
      - name: "Call API 2"
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.ES_URL }}/_aliases
          headers: '{ "Content-Type": "application/json", "Authorization": "ApiKey ${{ secrets.ES_WRITE_KEY_TEST }}" }'
          method: "POST"
          #body: '{ "actions": [ { "remove": { "index": "*", "alias": "${{ secrets.ES_INDEX_TEST }}--deploy-preview-alias-curl" } },{ "add": { "indices": ["${{ secrets.ES_INDEX_PREFIX_TEST }}-deploy-preview-index","${{ secrets.LIBGUIDES_ES_INDEX_TEST }}"], "alias": "${{ secrets.ES_INDEX_TEST }}--deploy-preview-alias-curl" } } ] }'
          log-response: true
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
      with:
        curl: "-H 'Content-Type: application/json' -H 'Authorization: ApiKey ${{ secrets.ES_WRITE_KEY_TEST }}' -X PUT ${{ secrets.ES_URL }}/_aliases"
  
  