name: Lint PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled

jobs:
  check-semantic-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: breaking,documentation,enhancement,feature,performance,refactor,bugfix,fix,chore,ci,test,
          repo_token: ${{ secrets.GITHUB_TOKEN }}
