name: nuxt3.x static site on stage

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        required: true
        default: nuxt3.x
        type: string

concurrency:
  group: deploy-stage
  cancel-in-progress: true

jobs:
  nuxt-deploy:
    name: Static Generation build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Cache built static site
        uses: actions/cache@v3
        with:
          path: .output/public
          key: nuxt-site-${{ github.sha }}
      - name: Sets env vars for stage
        run: |
          echo "CRAFT_ENDPOINT=${{secrets.CRAFT_PROD_ENDPOINT}}" >> $GITHUB_ENV
          echo "SITEMAP_HOST=${{secrets.SITEMAP_URL_STAGE}}" >> $GITHUB_ENV
          echo "NETLIFY_SITE_ID=${{secrets.NETLIFY_STAGE_LIBRARY_SITE_ID}}" >> $GITHUB_ENV
          echo "ES_READ_KEY=${{secrets.ES_READ_KEY_STAGE}}" >> $GITHUB_ENV
          echo "ES_WRITE_KEY=${{secrets.ES_WRITE_KEY_STAGE}}" >> $GITHUB_ENV
          echo "ES_ALIAS=${{secrets.ES_ALIAS_STAGE}}" >> $GITHUB_ENV
          echo "ES_INDEX_PREFIX=${{secrets.ES_INDEX_PREFIX_STAGE}}" >> $GITHUB_ENV
          echo "LIBGUIDES_ES_INDEX=${{secrets.LIBGUIDES_ES_INDEX_STAGE}}" >> $GITHUB_ENV
          echo "ES_TEMP_INDEX_PREFIX_LIBGUIDES=${{secrets.ES_TEMP_INDEX_PREFIX_LIBGUIDES_STAGE}}" >> $GITHUB_ENV
      - run: pnpm run generate
        env:
          CRAFT_ENDPOINT: ${{env.CRAFT_ENDPOINT}}
          S3_BUCKET: 'https://static.library.ucla.edu/'
          SITEMAP_HOST: ${{env.SITEMAP_HOST}}
          ES_URL: ${{ secrets.ES_URL }}
          ESApiKey: ${{ secrets.ESApiKey }}
          LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
          ES_READ_KEY: ${{env.ES_READ_KEY}}
          ES_WRITE_KEY: ${{env.ES_WRITE_KEY}}
          ES_ALIAS: ${{env.ES_ALIAS}}
          ES_INDEX_PREFIX: ${{env.ES_INDEX_PREFIX}}
          ES_TEMP_INDEX_PREFIX_LIBGUIDES: ${{env.ES_TEMP_INDEX_PREFIX_LIBGUIDES}}
          LIBGUIDES_ES_INDEX: ${{env.LIBGUIDES_ES_INDEX}}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          production-deploy: true
          deploy-message: https://github.com/UCLALibrary/library-website-nuxt/commit/${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: .output/public
          fails-without-credentials: true
          github-deployment-environment: production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
