name: Website Release

# Performs a Website release using Netlify when a new GitHub release has been published
on:
  release:
    types: [ published ]

jobs:
  nuxt-prod:
    name: Netlify deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: ./.github/workflows/setup-workspace
    - name: Cache built static site
      uses: actions/cache@v3
      with:
        path: ./dist
        key: nuxt-site-${{ github.sha }}
    - run: npm run generate
      env:
        CRAFT_ENDPOINT: ${{ secrets.CRAFT_PROD_ENDPOINT }}
        LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
        S3_BUCKET: "https://static.library.ucla.edu/"
        SITEMAP_HOST: "https://uclalibrary.library.ucla.edu"
        ES_URL: ${{ secrets.ES_URL }}
        ESApiKey: ${{ secrets.ESApiKey }}
        ES_READ_KEY: ${{ secrets.ES_READ_KEY_PROD }}
        ES_WRITE_KEY: ${{ secrets.ES_WRITE_KEY_PROD }}
        ES_INDEX: ${{ secrets.ES_INDEX_PROD }}
    - name: Deploy to Netlify on release
      uses: nwtgck/actions-netlify@v2 #
      with:
        production-deploy: true
        deploy-message: https://github.com/UCLALibrary/library-website-nuxt/commit/${{ github.sha }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish-dir: './dist'
        fails-without-credentials: true
        github-deployment-environment: production
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROD_LIBRARY_SITE_ID }}
