name: delete preview on PR close

# only trigger on pull request closed events
on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  delete_preview:
    runs-on: ubuntu-20.04
    env:
      DEPLOY_PATH: ${{github.ref_name}}

    steps:
      - name: make empty dir
        run: mkdir empty
      - name: delete folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./empty
          destination_dir: ${{ env.PR_PATH }}
      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "🪓 PR closed, deleted preview at https://github.com/${{ github.repository }}/tree/gh-pages/${{ env.PR_PATH }}/"
