name: On release

on:
  release:
    types: [ published ]
  pull_request:


jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: git tag -f tagtest
      - run: git push -f origin tagtest
      # - uses: rickstaa/action-create-tag@v1
      #   with:
      #     tag: "tagtest"
      #     message: "set tagtest to second commit in branch (override first)"
      #     # tag: "production"
      #     # message: "Current production release, this tag is used to deploy"
      #     force_push_tag: true # force push to overwrite previous "production" tag
