name: Submit screenshots to Percy for visual regression testing.

on:
  push:
    branches: [nuxt3.x]
  workflow_dispatch:
    inputs: {}

jobs:
  percy-integration:
    name: Percy - Nuxt3.x Site
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-workspace
      - name: Sets env vars for PR preview
        run: |
          echo "ES_ALIAS=${{secrets.ES_ALIAS_TEST}}-percy-tests-${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
        if: github.ref_name!='nuxt3.x'
      - name: Sets env vars for nuxt3.x merge
        run: |
          echo "ES_ALIAS=${{secrets.ES_ALIAS_TEST}}" >> $GITHUB_ENV
        if: github.ref_name=='nuxt3.x'
      - run: pnpm run generate
        if: steps.cache-nuxt.outputs.cache-hit != 'true'
        env:
          CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT }}
          LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
          S3_BUCKET: 'https://static.library.ucla.edu/'
          ES_URL: ${{ secrets.ES_URL }}
          ESApiKey: ${{ secrets.ESApiKey }}
          ES_READ_KEY: ${{ secrets.ES_READ_KEY_TEST }}
          ES_WRITE_KEY: ${{ secrets.ES_WRITE_KEY_TEST }}
          ES_ALIAS: ${{ env.ES_ALIAS }}
          ES_INDEX_PREFIX: ${{secrets.ES_INDEX_PREFIX_TEST}}
          ES_TEMP_INDEX_PREFIX_LIBGUIDES: ${{secrets.ES_TEMP_INDEX_PREFIX_LIBGUIDES_TEST}}
          LIBGUIDES_ES_INDEX: ${{secrets.LIBGUIDES_ES_INDEX_TEST}}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: cypress-io/github-action@v5
        with:
          start: pnpm dlx serve .output/public
          install: false
          command-prefix: 'percy exec -- pnpx'
          wait-on: http://localhost:3000
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_NUXT3X_E2E }}
          PERCY_TARGET_BRANCH: nuxt3.x

