name: Submit screenshots to Percy for visual regression testing.

on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs: {}

jobs:
    percy:
        name: Percy - Nuxt Site
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/workflows/setup-workspace
            - name: Cache built static site
              id: cache-nuxt
              uses: actions/cache@v3
              with:
                  path: .output/public
                  key: nuxt-site-${{ github.sha }}
            - run: npm run generate
              if: steps.cache-nuxt.outputs.cache-hit != 'true'
              env:
                  CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT_TEST }}
                  S3_BUCKET: "https://static.library.ucla.edu/"
                  ES_URL: ${{ secrets.ES_URL }}
                  ESApiKey: ${{ secrets.ESApiKey }}
                  ES_READ_KEY: ${{ secrets.ES_READ_KEY_TEST }}
                  ES_WRITE_KEY: ${{ secrets.ES_WRITE_KEY_TEST }}
                  ES_ALIAS: ${{ env.ES_ALIAS }}-${{ github.event.pull_request.number }}
                  ES_INDEX_PREFIX: ${{secrets.ES_INDEX_PREFIX_TEST}}
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 10
            - uses: cypress-io/github-action@v3
              with:
                  start: pnpm dlx serve .output/public
                  command-prefix: "percy exec -- pnpx"
                  install: false
                  wait-on: http://localhost:3000
                  wait-on-timeout: 110
              env:
                  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
                  CYPRESS_VISUAL_PROVIDER: percy
