name:  Submit screenshots to Percy for visual regression testing.

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs: {}

jobs:
  percy-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
      with:
        node-version: '14.15.4'
        cache: 'npm'
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm ci
    - name: Cache Storybook Build
      id: cache-storybook
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: storybook-static
        key: storybook-${{ github.sha }}
    - run: npm run storybook-build
      if: steps.cache-storybook.outputs.cache-hit != 'true'
    - run: npm run percy-static
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  percy-cypress:
    name: Cypress tests with Percy screenshots
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: ./.github/workflows/setup-workspace
    - name: Cache built static site
      id: cache-nuxt
      uses: actions/cache@v2
      with:
        path: ./dist
        key: nuxt-site-${{ github.sha }}
    - run: npm run generate
      if: steps.cache-nuxt.outputs.cache-hit != 'true'
      env:
        CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT }}
        LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
        LIBCAL_CLIENT_SECRET: ${{ secrets.LIBCAL_CLIENT_SECRET }}
        LIBCAL_CLIENT_ID: ${{ secrets.LIBCAL_CLIENT_ID }}
    - uses: cypress-io/github-action@2113e5bc19c45979ba123df6e07256d2aaba9a33
      with:
        start: docker run -v ${{ github.workspace }}/dist:/usr/share/nginx/html:ro -p 3000:80 nginx
        command-prefix: 'percy exec -- npx'
        wait-on: http://localhost:3000
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
