name:  Submit screenshots to Percy for visual regression testing.

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs: {}

jobs:
  percy:
    name: Percy - Nuxt Site
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: ./.github/workflows/setup-workspace
    - name: Cache built static site
      id: cache-nuxt
      uses: actions/cache@v2
      with:
        path: ./dist
        key: nuxt-site-${{ github.sha }}
    - run: npm run generate
      if: steps.cache-nuxt.outputs.cache-hit != 'true'
      env:
        CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT_TEST }}
        LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
        LIBCAL_CLIENT_SECRET: ${{ secrets.LIBCAL_CLIENT_SECRET }}
        LIBCAL_CLIENT_ID: ${{ secrets.LIBCAL_CLIENT_ID }}
        S3_BUCKET: "https://static.library.ucla.edu/"
        LIVE_PREVIEW: "dev"
    - uses: cypress-io/github-action@2113e5bc19c45979ba123df6e07256d2aaba9a33
      with:
        start: npx http-server ./dist -p 3000
        command-prefix: 'percy exec -- npx'
        wait-on: http://localhost:3000
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
