name:  Submit screenshots to Percy for visual regression testing.

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs: {}

jobs:
  percy-integration:
    name: Percy - Nuxt Site
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DEPLOY_URL: https://uclalibrary.github.io/library-website-nuxt/${{github.ref_name}}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/setup-workspace
    - name: Cache built static site
      id: cache-nuxt
      uses: actions/cache@v3
      with:
        path: ./dist
        key: nuxt-site-${{ github.sha }}
    - run: npm run generate
      if: steps.cache-nuxt.outputs.cache-hit != 'true'
      env:
        CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT }}
        LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
        S3_BUCKET: "https://static.library.ucla.edu/"
        ES_URL: ${{ secrets.ES_URL }}
        ESApiKey: ${{ secrets.ESApiKey }}
    - uses: cypress-io/github-action@v3
      with:
        command-prefix: 'percy exec -- npx'
        wait-on:  ${{ env.DEPLOY_URL }}
      env: 
        CYPRESS_baseUrl: ${{ env.DEPLOY_URL }}
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_E2E }}
          CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT }}
          LIBCAL_ENDPOINT: ${{ secrets.LIBCAL_ENDPOINT }}
          S3_BUCKET: "https://static.library.ucla.edu/"
          SITEMAP_HOST: "https://uclalibrary-test.library.ucla.edu"
          ES_URL: ${{ secrets.ES_URL }}
          ESApiKey: ${{ secrets.ESApiKey }}
          ES_READ_KEY: ${{ secrets.ES_READ_KEY_TEST }}
          ES_WRITE_KEY: ${{ secrets.ES_WRITE_KEY_TEST }}
          ES_INDEX: ${{ secrets.ES_INDEX_TEST }}
