name: Draft Release

# Any time new commits hit the 'main' branch, add them to the next release draft
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  draft-release-notes:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@4d1215c66d92eba9557a55da848b2281a1a19235 # v5.13.0
        with:
          config-name: configs/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
